/**
 * MicroRadicle cultivar seeder.
 * Writes camelCase Crop JSON to src/data/crops/ and merges pack-shed storage specs.
 * Existing 24 demo-farm cultivars are NEVER overwritten (tests lock their identities).
 *
 * Run: node --experimental-strip-types scripts/seed-cultivars.ts
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type {
  CellSize,
  Crop,
  CropCategory,
  FertilityDemand,
  FrostHardiness,
  PropagationMethod,
  SalesUnit,
} from "../src/types/crop.ts";
import type {
  CoolingMethod,
  CropPostHarvestSpec,
  RespirationRating,
  StorageThermalZone,
} from "../src/types/economics.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const cropDir = join(root, "src/data/crops");
const storagePath = join(root, "src/data/economics/storageSpecs.json");

export const PRESERVE_IDS = [
  "arugula-astro",
  "basil-genovese",
  "bean-provider",
  "beet-chioggia",
  "broccoli-arcadia",
  "carrot-nantes-bolero",
  "carrot-yaya",
  "chard-bright-lights",
  "cilantro-santo",
  "cucumber-marketmore-76",
  "fennel-orion",
  "kale-red-russian",
  "kale-winterbor",
  "lettuce-romaine-green-forest",
  "lettuce-salanova-butterhead",
  "lettuce-salanova-red-oak",
  "onion-redwing",
  "pea-sugar-snap",
  "pepper-carmen",
  "radish-french-breakfast",
  "spinach-corvair",
  "squash-costata-romanesco",
  "tomato-cherry-sun-gold",
  "tomato-mountain-merit",
] as const;

const PRESERVE = new Set<string>(PRESERVE_IDS);

type Geom = Crop["fieldGeometry"];
type Irr = Crop["irrigationProfile"];
type Store = Omit<CropPostHarvestSpec, "crop_id">;

type Template = {
  commonName: string;
  botanicalName: string;
  family: string;
  category: CropCategory;
  method: PropagationMethod;
  cell: CellSize | null;
  nursery: number;
  germDays: number;
  germMin: number;
  germOpt: number;
  germMax: number;
  geom: Geom;
  dtm: number;
  holding: number;
  multicut: boolean;
  regrowth: number | null;
  harvests: number;
  fall: number;
  frost: FrostHardiness;
  unit: SalesUnit;
  unitsFt: number;
  ozUnit: number;
  lbsFt: number;
  cull: number;
  whole: number;
  direct: number;
  irr: Irr;
  demand: FertilityDemand;
  n: number;
  p: number;
  k: number;
  interval: number;
  maxSucc: number;
  companions: string[];
  avoid: string[];
  notes: string;
  swatch: string;
  store: Store;
};

type Variant = {
  id: string;
  cultivar: string;
  commonName?: string;
  botanicalName?: string;
  family?: string;
  dtm?: number;
  holding?: number;
  frost?: FrostHardiness;
  swatch?: string;
  notes?: string;
  whole?: number;
  direct?: number;
  lbsFt?: number;
  unitsFt?: number;
};

function r2(n: number): number {
  return Math.round(n * 100) / 100;
}

function geom(rows: 1 | 2 | 3 | 4 | 5 | 6, inRow: number, seed = inRow): Geom {
  return {
    standardBedWidthIn: 30,
    rowsPerBed: rows,
    inRowSpacingIn: inRow,
    seedSpacingIn: seed,
    plantsPerLinearFoot: r2(rows * (12 / inRow)),
  };
}

function irr(lines: 1 | 2 | 3 | 4, spacing: 4 | 8 | 12, gph: 0.25 | 0.42 | 0.5 | 0.65, weekIn: number): Irr {
  return { linesPerBed: lines, emitterSpacingIn: spacing, emitterGph: gph, weeklyWaterRequirementIn: weekIn };
}

function store(
  zone: StorageThermalZone,
  opt: number,
  min: number,
  max: number,
  rh: number,
  days: number,
  cool: CoolingMethod,
  resp: RespirationRating,
  cp: number,
  totes: number,
  hours: number,
): Store {
  return {
    storage_zone: zone,
    optimal_temp_f: opt,
    min_safe_temp_f: min,
    max_temp_f: max,
    optimal_rh_pct: rh,
    shelf_life_days: days,
    cooling_method: cool,
    respiration_rate_rating: resp,
    sensible_heat_btu_per_lb: cp,
    totes_per_100_lbs: totes,
    harvest_hours_per_100_bed_ft: hours,
  };
}

const Z1_GREENS = store("zone-1-cold-wet", 34, 32, 38, 98, 12, "hydrocooling", "high", 0.96, 4.5, 1.2);
const Z1_SPINACH = store("zone-1-cold-wet", 32, 32, 36, 95, 7, "hydrocooling", "extremely-high", 0.94, 5, 1.6);
const Z1_ROOT = store("zone-1-cold-wet", 32, 32, 40, 98, 90, "hydrocooling", "low", 0.9, 2.5, 2);
const Z1_RADISH = store("zone-1-cold-wet", 32, 32, 36, 95, 14, "hydrocooling", "moderate", 0.93, 3, 1.2);
const Z1_BRASS = store("zone-1-cold-wet", 32, 32, 36, 95, 14, "ice-top", "extremely-high", 0.92, 3, 1.8);
const Z1_KALE = store("zone-1-cold-wet", 32, 32, 40, 95, 14, "hydrocooling", "high", 0.9, 3.5, 1.4);
const Z2_FRUIT = store("zone-2-cool-humid", 50, 50, 55, 90, 7, "forced-air", "moderate", 0.94, 2.5, 2.2);
const Z2_PEPPER = store("zone-2-cool-humid", 50, 45, 55, 90, 14, "forced-air", "low", 0.92, 2.5, 2);
const Z2_CUC = store("zone-2-cool-humid", 50, 50, 55, 95, 10, "forced-air", "moderate", 0.97, 2.5, 1.5);
const Z2_SQUASH = store("zone-2-cool-humid", 50, 45, 55, 90, 10, "forced-air", "moderate", 0.95, 2.2, 1.6);
const Z2_BASIL = store("zone-2-cool-humid", 50, 50, 55, 90, 7, "room-cooling", "moderate", 0.92, 4, 2.4);
const Z2_BEAN = store("zone-2-cool-humid", 45, 40, 50, 90, 7, "forced-air", "high", 0.91, 3, 2);
const Z2_MELON = store("zone-2-cool-humid", 45, 40, 50, 90, 14, "forced-air", "moderate", 0.93, 2, 1.8);
const Z3_ONION = store("zone-3-ambient-dry", 55, 32, 60, 65, 180, "room-cooling", "very-low", 0.9, 2, 1.8);
const Z3_SQUASH = store("zone-3-ambient-dry", 55, 50, 60, 65, 90, "room-cooling", "low", 0.91, 1.8, 1.6);
const Z1_HERB = store("zone-1-cold-wet", 32, 32, 36, 95, 7, "hydrocooling", "high", 0.94, 4.5, 2);
const Z1_PEA = store("zone-1-cold-wet", 32, 32, 36, 95, 7, "forced-air", "high", 0.89, 3, 2.2);

function T(partial: Template): Template {
  return partial;
}

const S = {
  lettuceHead: T({
    commonName: "Lettuce",
    botanicalName: "Lactuca sativa",
    family: "Asteraceae",
    category: "leafy-greens",
    method: "transplant",
    cell: 128,
    nursery: 24,
    germDays: 5,
    germMin: 40,
    germOpt: 68,
    germMax: 80,
    geom: geom(4, 6, 0.5),
    dtm: 52,
    holding: 10,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.15,
    frost: "hardy",
    unit: "head",
    unitsFt: 8,
    ozUnit: 0.4,
    lbsFt: 3.2,
    cull: 0.08,
    whole: 1.75,
    direct: 3,
    irr: irr(2, 8, 0.42, 1),
    demand: "moderate",
    n: 1.4,
    p: 0.35,
    k: 1.6,
    interval: 7,
    maxSucc: 14,
    companions: ["carrot", "onion", "radish"],
    avoid: ["broccoli", "fennel"],
    notes: "30-inch 4-row 6 in. One-cut or full head. Shade 30% after June 1 in zone 7–8. Hold 34°F 98% RH.",
    swatch: "#86efac",
    store: Z1_GREENS,
  }),
  lettuceRomaine: T({
    commonName: "Romaine",
    botanicalName: "Lactuca sativa var. longifolia",
    family: "Asteraceae",
    category: "leafy-greens",
    method: "transplant",
    cell: 128,
    nursery: 26,
    germDays: 5,
    germMin: 40,
    germOpt: 68,
    germMax: 80,
    geom: geom(3, 8, 0.5),
    dtm: 58,
    holding: 12,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.15,
    frost: "hardy",
    unit: "head",
    unitsFt: 4.5,
    ozUnit: 0.7,
    lbsFt: 3.15,
    cull: 0.1,
    whole: 1.85,
    direct: 3.25,
    irr: irr(2, 8, 0.42, 1),
    demand: "moderate",
    n: 1.5,
    p: 0.38,
    k: 1.7,
    interval: 10,
    maxSucc: 10,
    companions: ["carrot", "onion", "radish"],
    avoid: ["broccoli"],
    notes: "3-row 8 in romaine on 30-inch. Tipburn watch in heat — Muir/Nevada class for summer.",
    swatch: "#4ade80",
    store: Z1_GREENS,
  }),
  lettuceLeaf: T({
    commonName: "Leaf lettuce",
    botanicalName: "Lactuca sativa var. crispa",
    family: "Asteraceae",
    category: "leafy-greens",
    method: "transplant",
    cell: 128,
    nursery: 22,
    germDays: 4,
    germMin: 40,
    germOpt: 68,
    germMax: 80,
    geom: geom(4, 6, 0.5),
    dtm: 40,
    holding: 8,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.2,
    frost: "moderate",
    unit: "head",
    unitsFt: 8,
    ozUnit: 0.35,
    lbsFt: 2.8,
    cull: 0.1,
    whole: 1.6,
    direct: 2.75,
    irr: irr(2, 8, 0.42, 1),
    demand: "moderate",
    n: 1.3,
    p: 0.32,
    k: 1.5,
    interval: 7,
    maxSucc: 14,
    companions: ["carrot", "onion"],
    avoid: ["broccoli"],
    notes: "Fast leaf for shoulder seasons. New Red Fire and Tropicana hold in heat better than butterheads.",
    swatch: "#f87171",
    store: Z1_GREENS,
  }),
  spinach: T({
    commonName: "Spinach",
    botanicalName: "Spinacia oleracea",
    family: "Amaranthaceae",
    category: "leafy-greens",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 7,
    germMin: 35,
    germOpt: 55,
    germMax: 68,
    geom: geom(5, 2, 1.5),
    dtm: 38,
    holding: 7,
    multicut: true,
    regrowth: 14,
    harvests: 2,
    fall: 1.35,
    frost: "extreme",
    unit: "pound",
    unitsFt: 1.2,
    ozUnit: 1,
    lbsFt: 1.2,
    cull: 0.1,
    whole: 6,
    direct: 10,
    irr: irr(3, 8, 0.42, 1),
    demand: "moderate",
    n: 1.2,
    p: 0.3,
    k: 1.4,
    interval: 14,
    maxSucc: 6,
    companions: ["strawberry", "pea", "allium"],
    avoid: ["potato"],
    notes: "5-line Jang on 30-inch. Bolts after 14-h days. Space/Gazelle for spring, Flamingo for fall.",
    swatch: "#166534",
    store: Z1_SPINACH,
  }),
  arugula: T({
    commonName: "Arugula",
    botanicalName: "Eruca vesicaria",
    family: "Brassicaceae",
    category: "leafy-greens",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 4,
    germMin: 40,
    germOpt: 70,
    germMax: 85,
    geom: geom(5, 1.5, 1),
    dtm: 28,
    holding: 5,
    multicut: true,
    regrowth: 12,
    harvests: 2,
    fall: 1.3,
    frost: "hardy",
    unit: "pound",
    unitsFt: 0.5,
    ozUnit: 1,
    lbsFt: 0.5,
    cull: 0.12,
    whole: 8,
    direct: 12,
    irr: irr(2, 8, 0.42, 0.9),
    demand: "light",
    n: 0.9,
    p: 0.22,
    k: 1,
    interval: 10,
    maxSucc: 12,
    companions: ["lettuce", "carrot"],
    avoid: ["strawberry"],
    notes: "Baby at 21 d, bunch at 28–35. Sylvetta (wild) is slower and more pungent. Flea beetle: insect net.",
    swatch: "#65a30d",
    store: Z1_GREENS,
  }),
  chard: T({
    commonName: "Chard",
    botanicalName: "Beta vulgaris subsp. vulgaris",
    family: "Amaranthaceae",
    category: "leafy-greens",
    method: "transplant",
    cell: 128,
    nursery: 28,
    germDays: 6,
    germMin: 50,
    germOpt: 75,
    germMax: 85,
    geom: geom(2, 10, 2),
    dtm: 50,
    holding: 60,
    multicut: true,
    regrowth: 10,
    harvests: 8,
    fall: 1.1,
    frost: "hardy",
    unit: "bunch",
    unitsFt: 2.4,
    ozUnit: 0.7,
    lbsFt: 1.7,
    cull: 0.08,
    whole: 2.5,
    direct: 4,
    irr: irr(2, 8, 0.42, 1.1),
    demand: "moderate",
    n: 1.6,
    p: 0.4,
    k: 2.2,
    interval: 21,
    maxSucc: 3,
    companions: ["allium", "lettuce", "bean"],
    avoid: ["spinach"],
    notes: "Cut-and-come-again. Barese for baby; Fordhook for bulk bunches. Leaf miner: row cover until 8 in.",
    swatch: "#f97316",
    store: Z1_GREENS,
  }),
  asianGreen: T({
    commonName: "Asian green",
    botanicalName: "Brassica rapa",
    family: "Brassicaceae",
    category: "leafy-greens",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 4,
    germMin: 45,
    germOpt: 70,
    germMax: 85,
    geom: geom(4, 4, 1),
    dtm: 32,
    holding: 7,
    multicut: true,
    regrowth: 10,
    harvests: 3,
    fall: 1.25,
    frost: "hardy",
    unit: "pound",
    unitsFt: 0.8,
    ozUnit: 1,
    lbsFt: 0.8,
    cull: 0.1,
    whole: 6,
    direct: 10,
    irr: irr(2, 8, 0.42, 1),
    demand: "moderate",
    n: 1.2,
    p: 0.3,
    k: 1.4,
    interval: 10,
    maxSucc: 8,
    companions: ["lettuce", "allium"],
    avoid: ["strawberry"],
    notes: "Flea beetle net from sow. Mei Qing Choi and Joy Choi size for bunches; mizuna for salad mix.",
    swatch: "#22c55e",
    store: Z1_GREENS,
  }),
  kale: T({
    commonName: "Kale",
    botanicalName: "Brassica oleracea var. sabellica",
    family: "Brassicaceae",
    category: "brassicas",
    method: "transplant",
    cell: 128,
    nursery: 32,
    germDays: 6,
    germMin: 40,
    germOpt: 68,
    germMax: 80,
    geom: geom(2, 12, 2),
    dtm: 55,
    holding: 40,
    multicut: true,
    regrowth: 12,
    harvests: 8,
    fall: 1.05,
    frost: "extreme",
    unit: "bunch",
    unitsFt: 1.6,
    ozUnit: 0.75,
    lbsFt: 1.2,
    cull: 0.08,
    whole: 2.5,
    direct: 4,
    irr: irr(2, 8, 0.42, 1.1),
    demand: "heavy",
    n: 2.2,
    p: 0.55,
    k: 2.4,
    interval: 21,
    maxSucc: 3,
    companions: ["allium", "beet", "lettuce"],
    avoid: ["strawberry", "tomato"],
    notes: "2-row 12 in. Strip lower leaves weekly. Cabbage aphid: net or weekly scout. Sweetens after frost.",
    swatch: "#15803d",
    store: Z1_KALE,
  }),
  broccoli: T({
    commonName: "Broccoli",
    botanicalName: "Brassica oleracea var. italica",
    family: "Brassicaceae",
    category: "brassicas",
    method: "transplant",
    cell: 128,
    nursery: 28,
    germDays: 5,
    germMin: 45,
    germOpt: 70,
    germMax: 85,
    geom: geom(2, 15, 2),
    dtm: 62,
    holding: 7,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.15,
    frost: "hardy",
    unit: "head",
    unitsFt: 1.3,
    ozUnit: 0.85,
    lbsFt: 1.1,
    cull: 0.12,
    whole: 2.5,
    direct: 4,
    irr: irr(2, 8, 0.5, 1.4),
    demand: "heavy",
    n: 2.6,
    p: 0.7,
    k: 2.8,
    interval: 14,
    maxSucc: 3,
    companions: ["allium", "beet"],
    avoid: ["tomato", "strawberry"],
    notes: "Even moisture or hollow stem. Gypsy/Belstar for heat; Imperial for fall. Ice immediately.",
    swatch: "#4ade80",
    store: Z1_BRASS,
  }),
  cabbage: T({
    commonName: "Cabbage",
    botanicalName: "Brassica oleracea var. capitata",
    family: "Brassicaceae",
    category: "brassicas",
    method: "transplant",
    cell: 128,
    nursery: 28,
    germDays: 5,
    germMin: 45,
    germOpt: 70,
    germMax: 85,
    geom: geom(2, 12, 2),
    dtm: 55,
    holding: 14,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.15,
    frost: "hardy",
    unit: "head",
    unitsFt: 2,
    ozUnit: 1.5,
    lbsFt: 3,
    cull: 0.1,
    whole: 1.5,
    direct: 3,
    irr: irr(2, 8, 0.5, 1.25),
    demand: "heavy",
    n: 2.4,
    p: 0.6,
    k: 2.6,
    interval: 18,
    maxSucc: 3,
    companions: ["allium", "dill"],
    avoid: ["strawberry"],
    notes: "Tiara/Farao for mini heads on 12 in. Split after rain — harvest tight. Net vs cabbageworm.",
    swatch: "#86efac",
    store: Z1_BRASS,
  }),
  cauliflower: T({
    commonName: "Cauliflower",
    botanicalName: "Brassica oleracea var. botrytis",
    family: "Brassicaceae",
    category: "brassicas",
    method: "transplant",
    cell: 128,
    nursery: 32,
    germDays: 6,
    germMin: 45,
    germOpt: 68,
    germMax: 80,
    geom: geom(2, 18, 2),
    dtm: 70,
    holding: 7,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.2,
    frost: "hardy",
    unit: "head",
    unitsFt: 1.1,
    ozUnit: 1.2,
    lbsFt: 1.3,
    cull: 0.15,
    whole: 2.75,
    direct: 4.5,
    irr: irr(2, 8, 0.5, 1.5),
    demand: "heavy",
    n: 2.8,
    p: 0.75,
    k: 3,
    interval: 14,
    maxSucc: 2,
    companions: ["allium"],
    avoid: ["tomato"],
    notes: "Self-blanching types (Skywalker) skip tying. Heat = riciness. Fall crop is the money crop.",
    swatch: "#e5e7eb",
    store: Z1_BRASS,
  }),
  kohlrabi: T({
    commonName: "Kohlrabi",
    botanicalName: "Brassica oleracea var. gongylodes",
    family: "Brassicaceae",
    category: "brassicas",
    method: "transplant",
    cell: 128,
    nursery: 24,
    germDays: 5,
    germMin: 45,
    germOpt: 70,
    germMax: 85,
    geom: geom(3, 6, 1),
    dtm: 45,
    holding: 10,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.15,
    frost: "hardy",
    unit: "bunch",
    unitsFt: 4,
    ozUnit: 0.6,
    lbsFt: 2.4,
    cull: 0.1,
    whole: 2,
    direct: 3.5,
    irr: irr(2, 8, 0.42, 1.1),
    demand: "moderate",
    n: 1.6,
    p: 0.4,
    k: 1.8,
    interval: 14,
    maxSucc: 4,
    companions: ["beet", "allium"],
    avoid: ["strawberry"],
    notes: "Pick at tennis-ball or it lignifies. Kolibri (purple) outsells green at market.",
    swatch: "#c084fc",
    store: Z1_ROOT,
  }),
  carrot: T({
    commonName: "Carrot",
    botanicalName: "Daucus carota subsp. sativus",
    family: "Apiaceae",
    category: "root-crops",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 12,
    germMin: 45,
    germOpt: 75,
    germMax: 85,
    geom: geom(5, 1, 0.75),
    dtm: 70,
    holding: 21,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.12,
    frost: "hardy",
    unit: "pound",
    unitsFt: 2.2,
    ozUnit: 1,
    lbsFt: 2.2,
    cull: 0.12,
    whole: 1.5,
    direct: 2.75,
    irr: irr(2, 8, 0.42, 0.9),
    demand: "light",
    n: 0.9,
    p: 0.4,
    k: 2.2,
    interval: 21,
    maxSucc: 4,
    companions: ["lettuce", "onion", "radish", "pea"],
    avoid: ["dill", "parsnip"],
    notes: "Keep seedbed moist 14 d. Mokum/Nelson for bunching; Bolero/Romance for storage. No fresh manure.",
    swatch: "#fb923c",
    store: Z1_ROOT,
  }),
  radish: T({
    commonName: "Radish",
    botanicalName: "Raphanus sativus",
    family: "Brassicaceae",
    category: "root-crops",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 4,
    germMin: 45,
    germOpt: 70,
    germMax: 85,
    geom: geom(5, 1.5, 1),
    dtm: 26,
    holding: 4,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.25,
    frost: "hardy",
    unit: "bunch",
    unitsFt: 4,
    ozUnit: 0.45,
    lbsFt: 1.8,
    cull: 0.1,
    whole: 1.75,
    direct: 3,
    irr: irr(2, 8, 0.42, 0.9),
    demand: "light",
    n: 0.7,
    p: 0.2,
    k: 0.9,
    interval: 7,
    maxSucc: 12,
    companions: ["lettuce", "carrot"],
    avoid: [],
    notes: "Fast cash. Flea beetle net. Pull on time or pithy. Daikon is a different crop — 50–70 d, 3-row.",
    swatch: "#fca5a5",
    store: Z1_RADISH,
  }),
  beet: T({
    commonName: "Beet",
    botanicalName: "Beta vulgaris",
    family: "Amaranthaceae",
    category: "root-crops",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 7,
    germMin: 50,
    germOpt: 75,
    germMax: 85,
    geom: geom(4, 3, 2),
    dtm: 55,
    holding: 14,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.15,
    frost: "hardy",
    unit: "bunch",
    unitsFt: 3.2,
    ozUnit: 0.7,
    lbsFt: 2.2,
    cull: 0.1,
    whole: 2.25,
    direct: 3.75,
    irr: irr(2, 8, 0.42, 1),
    demand: "moderate",
    n: 1.3,
    p: 0.4,
    k: 2,
    interval: 18,
    maxSucc: 4,
    companions: ["allium", "lettuce", "kale"],
    avoid: ["mustard"],
    notes: "Seed is a corky cluster — thin to 3 in. Red Ace is the workhorse; Touchstone Gold stains less.",
    swatch: "#9f1239",
    store: Z1_ROOT,
  }),
  turnip: T({
    commonName: "Turnip",
    botanicalName: "Brassica rapa subsp. rapa",
    family: "Brassicaceae",
    category: "root-crops",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 4,
    germMin: 50,
    germOpt: 70,
    germMax: 85,
    geom: geom(4, 3, 2),
    dtm: 38,
    holding: 7,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.2,
    frost: "hardy",
    unit: "bunch",
    unitsFt: 3.2,
    ozUnit: 0.55,
    lbsFt: 1.75,
    cull: 0.1,
    whole: 2.25,
    direct: 3.75,
    irr: irr(2, 8, 0.42, 1),
    demand: "moderate",
    n: 1.1,
    p: 0.3,
    k: 1.6,
    interval: 14,
    maxSucc: 5,
    companions: ["pea", "allium"],
    avoid: [],
    notes: "Hakurei is the salad turnip — pick at 2 in. Flea beetle net. Greens are a second SKU.",
    swatch: "#f5f5f4",
    store: Z1_ROOT,
  }),
  onion: T({
    commonName: "Onion",
    botanicalName: "Allium cepa",
    family: "Amaryllidaceae",
    category: "alliums",
    method: "transplant",
    cell: 128,
    nursery: 70,
    germDays: 8,
    germMin: 50,
    germOpt: 68,
    germMax: 80,
    geom: geom(4, 4, 1),
    dtm: 105,
    holding: 21,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1,
    frost: "hardy",
    unit: "pound",
    unitsFt: 5,
    ozUnit: 1,
    lbsFt: 5,
    cull: 0.08,
    whole: 1.35,
    direct: 2.5,
    irr: irr(2, 8, 0.42, 1),
    demand: "moderate",
    n: 1.5,
    p: 0.55,
    k: 2.4,
    interval: 0,
    maxSucc: 1,
    companions: ["carrot", "beet", "lettuce", "kale"],
    avoid: ["pea", "bean"],
    notes: "Match day-length to latitude. Copra/Patterson long-day storage. Cure 2 weeks shade + airflow.",
    swatch: "#a78bfa",
    store: Z3_ONION,
  }),
  scallion: T({
    commonName: "Scallion",
    botanicalName: "Allium fistulosum",
    family: "Amaryllidaceae",
    category: "alliums",
    method: "transplant",
    cell: 200,
    nursery: 42,
    germDays: 7,
    germMin: 50,
    germOpt: 70,
    germMax: 80,
    geom: geom(4, 4, 1.5),
    dtm: 50,
    holding: 14,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.2,
    frost: "extreme",
    unit: "bunch",
    unitsFt: 3,
    ozUnit: 0.35,
    lbsFt: 1.05,
    cull: 0.1,
    whole: 1.75,
    direct: 3,
    irr: irr(2, 8, 0.42, 1),
    demand: "moderate",
    n: 1,
    p: 0.3,
    k: 1.3,
    interval: 21,
    maxSucc: 4,
    companions: ["carrot", "lettuce", "beet"],
    avoid: ["pea", "bean"],
    notes: "4 seeds/cell in 200s, plant the plug. Parade is the standard; Nabechan is sweeter.",
    swatch: "#86efac",
    store: Z1_GREENS,
  }),
  leek: T({
    commonName: "Leek",
    botanicalName: "Allium ampeloprasum",
    family: "Amaryllidaceae",
    category: "alliums",
    method: "transplant",
    cell: 128,
    nursery: 70,
    germDays: 10,
    germMin: 50,
    germOpt: 68,
    germMax: 80,
    geom: geom(3, 6, 1),
    dtm: 90,
    holding: 30,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1.05,
    frost: "extreme",
    unit: "pound",
    unitsFt: 2.4,
    ozUnit: 1,
    lbsFt: 2.4,
    cull: 0.08,
    whole: 2.5,
    direct: 4,
    irr: irr(2, 8, 0.42, 1.1),
    demand: "moderate",
    n: 1.4,
    p: 0.45,
    k: 1.8,
    interval: 0,
    maxSucc: 1,
    companions: ["carrot", "celery"],
    avoid: ["bean"],
    notes: "Dibble 6 in deep for blanch. King Richard for summer; Bandit/Tadorna overwinter.",
    swatch: "#4ade80",
    store: Z1_GREENS,
  }),
  garlic: T({
    commonName: "Garlic",
    botanicalName: "Allium sativum",
    family: "Amaryllidaceae",
    category: "alliums",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 21,
    germMin: 32,
    germOpt: 50,
    germMax: 70,
    geom: geom(4, 6, 6),
    dtm: 240,
    holding: 14,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1,
    frost: "extreme",
    unit: "pound",
    unitsFt: 1.6,
    ozUnit: 1,
    lbsFt: 1.6,
    cull: 0.08,
    whole: 6,
    direct: 10,
    irr: irr(2, 8, 0.42, 0.9),
    demand: "moderate",
    n: 1.2,
    p: 0.4,
    k: 1.6,
    interval: 0,
    maxSucc: 1,
    companions: ["beet", "lettuce", "kale"],
    avoid: ["pea", "bean"],
    notes: "Fall-planted cloves. Music is porcelain hardneck (scapes are a May SKU). Cure 3 weeks.",
    swatch: "#e7e5e4",
    store: Z3_ONION,
  }),
  tomatoCherry: T({
    commonName: "Cherry tomato",
    botanicalName: "Solanum lycopersicum",
    family: "Solanaceae",
    category: "solanaceous",
    method: "transplant",
    cell: 72,
    nursery: 49,
    germDays: 6,
    germMin: 60,
    germOpt: 78,
    germMax: 90,
    geom: geom(1, 18, 18),
    dtm: 60,
    holding: 70,
    multicut: true,
    regrowth: 3,
    harvests: 20,
    fall: 1,
    frost: "tender",
    unit: "pint",
    unitsFt: 5.5,
    ozUnit: 1.1,
    lbsFt: 6,
    cull: 0.1,
    whole: 3.25,
    direct: 5,
    irr: irr(1, 12, 0.5, 1.5),
    demand: "heavy",
    n: 2.6,
    p: 0.85,
    k: 4,
    interval: 21,
    maxSucc: 2,
    companions: ["basil", "carrot", "onion"],
    avoid: ["fennel", "potato", "brassica"],
    notes: "Single row, 7-ft stake or roll-and-pinch. Prune to 2–3 leaders. Pick daily at color break.",
    swatch: "#facc15",
    store: Z2_FRUIT,
  }),
  tomatoSlicer: T({
    commonName: "Tomato",
    botanicalName: "Solanum lycopersicum",
    family: "Solanaceae",
    category: "solanaceous",
    method: "transplant",
    cell: 72,
    nursery: 52,
    germDays: 6,
    germMin: 60,
    germOpt: 78,
    germMax: 90,
    geom: geom(1, 24, 24),
    dtm: 75,
    holding: 50,
    multicut: true,
    regrowth: 4,
    harvests: 12,
    fall: 1,
    frost: "tender",
    unit: "pound",
    unitsFt: 4,
    ozUnit: 1,
    lbsFt: 4,
    cull: 0.12,
    whole: 2.25,
    direct: 3.5,
    irr: irr(1, 12, 0.5, 1.6),
    demand: "heavy",
    n: 2.8,
    p: 0.9,
    k: 4.2,
    interval: 0,
    maxSucc: 1,
    companions: ["basil", "carrot", "onion"],
    avoid: ["fennel", "potato", "brassica"],
    notes: "Indeterminate on 30-inch, one row. Late blight: Defiant/Mountain Magic. Never refrigerate.",
    swatch: "#ef4444",
    store: Z2_FRUIT,
  }),
  pepper: T({
    commonName: "Pepper",
    botanicalName: "Capsicum annuum",
    family: "Solanaceae",
    category: "solanaceous",
    method: "transplant",
    cell: 72,
    nursery: 56,
    germDays: 10,
    germMin: 65,
    germOpt: 80,
    germMax: 90,
    geom: geom(2, 12, 12),
    dtm: 70,
    holding: 45,
    multicut: true,
    regrowth: 7,
    harvests: 8,
    fall: 1,
    frost: "tender",
    unit: "pound",
    unitsFt: 2.2,
    ozUnit: 1,
    lbsFt: 2.2,
    cull: 0.1,
    whole: 2.75,
    direct: 4.5,
    irr: irr(2, 8, 0.5, 1.4),
    demand: "heavy",
    n: 2,
    p: 0.6,
    k: 2.8,
    interval: 0,
    maxSucc: 1,
    companions: ["basil", "tomato", "onion"],
    avoid: ["fennel"],
    notes: "Bottom heat to germ. Carmen is the market-garden standard frying pepper. Pick turning color.",
    swatch: "#f97316",
    store: Z2_PEPPER,
  }),
  eggplant: T({
    commonName: "Eggplant",
    botanicalName: "Solanum melongena",
    family: "Solanaceae",
    category: "solanaceous",
    method: "transplant",
    cell: 72,
    nursery: 56,
    germDays: 10,
    germMin: 70,
    germOpt: 85,
    germMax: 95,
    geom: geom(1, 18, 18),
    dtm: 70,
    holding: 40,
    multicut: true,
    regrowth: 5,
    harvests: 10,
    fall: 1,
    frost: "tender",
    unit: "pound",
    unitsFt: 2.5,
    ozUnit: 1,
    lbsFt: 2.5,
    cull: 0.1,
    whole: 2.5,
    direct: 4,
    irr: irr(1, 12, 0.5, 1.5),
    demand: "heavy",
    n: 2.2,
    p: 0.65,
    k: 3,
    interval: 0,
    maxSucc: 1,
    companions: ["pepper", "bean"],
    avoid: ["fennel"],
    notes: "Flea beetle until flower. Nadia for Italian; Ichiban for Asian slender. Pick glossy, not dull.",
    swatch: "#6b21a8",
    store: Z2_PEPPER,
  }),
  cucumber: T({
    commonName: "Cucumber",
    botanicalName: "Cucumis sativus",
    family: "Cucurbitaceae",
    category: "cucurbits",
    method: "both",
    cell: 72,
    nursery: 21,
    germDays: 5,
    germMin: 60,
    germOpt: 80,
    germMax: 95,
    geom: geom(1, 12, 12),
    dtm: 52,
    holding: 35,
    multicut: true,
    regrowth: 2,
    harvests: 16,
    fall: 1,
    frost: "tender",
    unit: "pound",
    unitsFt: 7.6,
    ozUnit: 1,
    lbsFt: 7.6,
    cull: 0.08,
    whole: 1.25,
    direct: 2.1,
    irr: irr(1, 8, 0.5, 1.6),
    demand: "heavy",
    n: 1.8,
    p: 0.55,
    k: 2.4,
    interval: 14,
    maxSucc: 3,
    companions: ["bean", "pea", "radish"],
    avoid: ["potato", "sage"],
    notes: "Trellis one row. Corinto/Dasher for slicers. Pick every other day or they balloon.",
    swatch: "#4ade80",
    store: Z2_CUC,
  }),
  zucchini: T({
    commonName: "Zucchini",
    botanicalName: "Cucurbita pepo",
    family: "Cucurbitaceae",
    category: "cucurbits",
    method: "both",
    cell: 72,
    nursery: 18,
    germDays: 5,
    germMin: 60,
    germOpt: 85,
    germMax: 95,
    geom: geom(1, 24, 24),
    dtm: 48,
    holding: 28,
    multicut: true,
    regrowth: 2,
    harvests: 14,
    fall: 1,
    frost: "tender",
    unit: "pound",
    unitsFt: 6,
    ozUnit: 1,
    lbsFt: 6,
    cull: 0.1,
    whole: 1.4,
    direct: 2.5,
    irr: irr(1, 12, 0.5, 1.5),
    demand: "heavy",
    n: 1.7,
    p: 0.55,
    k: 2.2,
    interval: 14,
    maxSucc: 3,
    companions: ["bean", "nasturtium"],
    avoid: ["potato"],
    notes: "Dunja is PM-resistant. Pick 6–8 in daily. Squash bug: row cover until female flowers.",
    swatch: "#22c55e",
    store: Z2_SQUASH,
  }),
  winterSquash: T({
    commonName: "Winter squash",
    botanicalName: "Cucurbita moschata",
    family: "Cucurbitaceae",
    category: "cucurbits",
    method: "direct-seed",
    cell: 72,
    nursery: 18,
    germDays: 6,
    germMin: 60,
    germOpt: 85,
    germMax: 95,
    geom: geom(1, 24, 24),
    dtm: 95,
    holding: 14,
    multicut: false,
    regrowth: null,
    harvests: 1,
    fall: 1,
    frost: "tender",
    unit: "pound",
    unitsFt: 4,
    ozUnit: 1,
    lbsFt: 4,
    cull: 0.1,
    whole: 1.25,
    direct: 2,
    irr: irr(1, 12, 0.5, 1.3),
    demand: "heavy",
    n: 1.6,
    p: 0.5,
    k: 2.4,
    interval: 0,
    maxSucc: 1,
    companions: ["corn", "bean"],
    avoid: ["potato"],
    notes: "Cure 10 d at 80°F then Zone 3 dry. Honeynut is the high-value personal squash.",
    swatch: "#ea580c",
    store: Z3_SQUASH,
  }),
  melon: T({
    commonName: "Melon",
    botanicalName: "Cucumis melo",
    family: "Cucurbitaceae",
    category: "cucurbits",
    method: "transplant",
    cell: 72,
    nursery: 21,
    germDays: 5,
    germMin: 70,
    germOpt: 85,
    germMax: 95,
    geom: geom(1, 24, 24),
    dtm: 78,
    holding: 10,
    multicut: true,
    regrowth: 5,
    harvests: 4,
    fall: 1,
    frost: "tender",
    unit: "pound",
    unitsFt: 3.5,
    ozUnit: 1,
    lbsFt: 3.5,
    cull: 0.12,
    whole: 1.75,
    direct: 3,
    irr: irr(1, 12, 0.5, 1.5),
    demand: "moderate",
    n: 1.4,
    p: 0.45,
    k: 2.2,
    interval: 0,
    maxSucc: 1,
    companions: ["radish"],
    avoid: ["potato"],
    notes: "Plasticulture + drip. Slip when full slip (Sarah's Choice). Never ice below 40°F.",
    swatch: "#fbbf24",
    store: Z2_MELON,
  }),
  bean: T({
    commonName: "Snap bean",
    botanicalName: "Phaseolus vulgaris",
    family: "Fabaceae",
    category: "legumes",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 7,
    germMin: 60,
    germOpt: 80,
    germMax: 90,
    geom: geom(2, 3, 2),
    dtm: 54,
    holding: 12,
    multicut: true,
    regrowth: 5,
    harvests: 4,
    fall: 1.1,
    frost: "tender",
    unit: "pound",
    unitsFt: 1.4,
    ozUnit: 1,
    lbsFt: 1.4,
    cull: 0.1,
    whole: 2.75,
    direct: 4.5,
    irr: irr(2, 8, 0.42, 1),
    demand: "light",
    n: 0.8,
    p: 0.35,
    k: 1.2,
    interval: 14,
    maxSucc: 5,
    companions: ["carrot", "cucumber", "corn"],
    avoid: ["allium", "fennel"],
    notes: "Inoculate. Provider is cold-soil reliable; Jade is the dark-green market bean. Pick every 2 d.",
    swatch: "#16a34a",
    store: Z2_BEAN,
  }),
  pea: T({
    commonName: "Snap pea",
    botanicalName: "Pisum sativum",
    family: "Fabaceae",
    category: "legumes",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 10,
    germMin: 40,
    germOpt: 60,
    germMax: 75,
    geom: geom(2, 2, 1.5),
    dtm: 64,
    holding: 18,
    multicut: true,
    regrowth: 3,
    harvests: 8,
    fall: 1.1,
    frost: "hardy",
    unit: "pound",
    unitsFt: 1.2,
    ozUnit: 1,
    lbsFt: 1.2,
    cull: 0.1,
    whole: 3.5,
    direct: 6,
    irr: irr(2, 8, 0.42, 0.9),
    demand: "light",
    n: 0.7,
    p: 0.28,
    k: 1.1,
    interval: 14,
    maxSucc: 3,
    companions: ["carrot", "radish", "turnip"],
    avoid: ["allium"],
    notes: "Hortonova on 30-inch. Sugar Ann is extra-early dwarf; Oregon Giant for volume. Inoculate.",
    swatch: "#86efac",
    store: Z1_PEA,
  }),
  basil: T({
    commonName: "Basil",
    botanicalName: "Ocimum basilicum",
    family: "Lamiaceae",
    category: "herbs",
    method: "transplant",
    cell: 128,
    nursery: 28,
    germDays: 6,
    germMin: 65,
    germOpt: 78,
    germMax: 90,
    geom: geom(3, 8, 2),
    dtm: 50,
    holding: 20,
    multicut: true,
    regrowth: 12,
    harvests: 5,
    fall: 1,
    frost: "tender",
    unit: "bunch",
    unitsFt: 3.2,
    ozUnit: 0.22,
    lbsFt: 0.7,
    cull: 0.1,
    whole: 2,
    direct: 3.5,
    irr: irr(2, 8, 0.42, 1.1),
    demand: "moderate",
    n: 1,
    p: 0.3,
    k: 1.2,
    interval: 21,
    maxSucc: 3,
    companions: ["tomato", "pepper"],
    avoid: ["rue"],
    notes: "Pinch above second node. Downy mildew: Prospera/Eleonora. Never refrigerate — Zone 2 50°F.",
    swatch: "#16a34a",
    store: Z2_BASIL,
  }),
  cilantro: T({
    commonName: "Cilantro",
    botanicalName: "Coriandrum sativum",
    family: "Apiaceae",
    category: "herbs",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 8,
    germMin: 50,
    germOpt: 70,
    germMax: 80,
    geom: geom(4, 2, 1.5),
    dtm: 40,
    holding: 6,
    multicut: true,
    regrowth: 14,
    harvests: 2,
    fall: 1.25,
    frost: "hardy",
    unit: "bunch",
    unitsFt: 4,
    ozUnit: 0.2,
    lbsFt: 0.8,
    cull: 0.1,
    whole: 1.75,
    direct: 3,
    irr: irr(2, 8, 0.42, 0.95),
    demand: "light",
    n: 0.7,
    p: 0.22,
    k: 0.9,
    interval: 10,
    maxSucc: 10,
    companions: ["anise", "spinach"],
    avoid: ["fennel"],
    notes: "Calypso/Cruiser delay bolt. Succession weekly in heat. Hydrocool, 34°F, never wash until pack.",
    swatch: "#4ade80",
    store: Z1_HERB,
  }),
  parsley: T({
    commonName: "Parsley",
    botanicalName: "Petroselinum crispum",
    family: "Apiaceae",
    category: "herbs",
    method: "transplant",
    cell: 128,
    nursery: 42,
    germDays: 18,
    germMin: 50,
    germOpt: 70,
    germMax: 80,
    geom: geom(3, 6, 1),
    dtm: 70,
    holding: 40,
    multicut: true,
    regrowth: 14,
    harvests: 6,
    fall: 1.1,
    frost: "hardy",
    unit: "bunch",
    unitsFt: 3,
    ozUnit: 0.25,
    lbsFt: 0.75,
    cull: 0.08,
    whole: 1.5,
    direct: 2.5,
    irr: irr(2, 8, 0.42, 1),
    demand: "moderate",
    n: 0.9,
    p: 0.28,
    k: 1.1,
    interval: 0,
    maxSucc: 2,
    companions: ["tomato", "asparagus"],
    avoid: [],
    notes: "Slow germ — soak seed. Giant of Italy is the flat-leaf standard. Overwinters in zone 7.",
    swatch: "#15803d",
    store: Z1_HERB,
  }),
  dill: T({
    commonName: "Dill",
    botanicalName: "Anethum graveolens",
    family: "Apiaceae",
    category: "herbs",
    method: "direct-seed",
    cell: null,
    nursery: 0,
    germDays: 8,
    germMin: 50,
    germOpt: 70,
    germMax: 80,
    geom: geom(3, 4, 1),
    dtm: 40,
    holding: 10,
    multicut: true,
    regrowth: 10,
    harvests: 3,
    fall: 1.15,
    frost: "moderate",
    unit: "bunch",
    unitsFt: 2.5,
    ozUnit: 0.2,
    lbsFt: 0.5,
    cull: 0.1,
    whole: 1.5,
    direct: 2.5,
    irr: irr(2, 8, 0.42, 0.9),
    demand: "light",
    n: 0.6,
    p: 0.2,
    k: 0.8,
    interval: 14,
    maxSucc: 6,
    companions: ["cabbage", "onion"],
    avoid: ["carrot"],
    notes: "Bouquet for leaf; let a row go to flower for pickling umbels. Fernleaf is compact.",
    swatch: "#65a30d",
    store: Z1_HERB,
  }),
  herbPerennial: T({
    commonName: "Herb",
    botanicalName: "Lamiaceae",
    family: "Lamiaceae",
    category: "herbs",
    method: "transplant",
    cell: 128,
    nursery: 35,
    germDays: 10,
    germMin: 55,
    germOpt: 70,
    germMax: 85,
    geom: geom(3, 8, 2),
    dtm: 50,
    holding: 60,
    multicut: true,
    regrowth: 14,
    harvests: 6,
    fall: 1,
    frost: "moderate",
    unit: "bunch",
    unitsFt: 2.4,
    ozUnit: 0.15,
    lbsFt: 0.36,
    cull: 0.08,
    whole: 2,
    direct: 3.5,
    irr: irr(2, 8, 0.42, 0.8),
    demand: "light",
    n: 0.5,
    p: 0.18,
    k: 0.7,
    interval: 0,
    maxSucc: 1,
    companions: ["cabbage", "tomato"],
    avoid: [],
    notes: "Woody herbs on 30-inch, 3-row. Don't overwater. Zone 2 for basil-family; dry for thyme/oregano.",
    swatch: "#84cc16",
    store: Z2_BASIL,
  }),
} as const satisfies Record<string, Template>;

type SpeciesKey = keyof typeof S;

const VARIANTS: Array<{ species: SpeciesKey } & Variant> = [
  // —— leafy greens ——
  { species: "lettuceHead", id: "lettuce-salanova-green-butter", cultivar: "Salanova Green Butter", botanicalName: "Lactuca sativa var. capitata", swatch: "#86efac", notes: "One-cut green butter. Core snap, 10–12 uniform leaves. Same 4-row 6 in as Salanova Butterhead." },
  { species: "lettuceHead", id: "lettuce-salanova-green-oak", cultivar: "Salanova Green Oak", dtm: 50, swatch: "#4ade80" },
  { species: "lettuceHead", id: "lettuce-salanova-red-butter", cultivar: "Salanova Red Butter", dtm: 54, swatch: "#e11d48" },
  { species: "lettuceHead", id: "lettuce-salanova-incised", cultivar: "Salanova Incised", dtm: 48, swatch: "#bbf7d0" },
  { species: "lettuceHead", id: "lettuce-butterhead-nancy", cultivar: "Nancy", dtm: 52, notes: "Classic Boston. Soft head, 4-row 6 in. Springs best; shades in June." },
  { species: "lettuceHead", id: "lettuce-butterhead-skyphos", cultivar: "Skyphos", dtm: 48, swatch: "#b91c1c", notes: "Red Boston. Holds in heat better than Nancy. 4-row 6 in." },
  { species: "lettuceHead", id: "lettuce-butterhead-adriana", cultivar: "Adriana", dtm: 48, notes: "Heat-tolerant butterhead. Summer slot when Salanova tips." },
  { species: "lettuceHead", id: "lettuce-little-gem-trifecta", cultivar: "Trifecta", dtm: 48, unitsFt: 8, notes: "Mini romaine/little gem. Dense 4-row. High count per tote." },
  { species: "lettuceRomaine", id: "lettuce-romaine-coastal-star", cultivar: "Coastal Star", dtm: 65, notes: "Full-size green romaine. 3-row 8 in. Slow bolt." },
  { species: "lettuceRomaine", id: "lettuce-romaine-dragoon", cultivar: "Dragoon", dtm: 51, notes: "Mini romaine, dense. High piece count. 3-row 8 in or 4-row 6 in." },
  { species: "lettuceRomaine", id: "lettuce-romaine-palomino", cultivar: "Palomino", dtm: 58, swatch: "#fde68a" },
  { species: "lettuceRomaine", id: "lettuce-romaine-plato", cultivar: "Plato", dtm: 60 },
  { species: "lettuceRomaine", id: "lettuce-batavia-muir", cultivar: "Muir", dtm: 50, botanicalName: "Lactuca sativa", notes: "Summer Batavia. Tipburn resistant. The July lettuce." },
  { species: "lettuceRomaine", id: "lettuce-batavia-nevada", cultivar: "Nevada", dtm: 52, notes: "Green Batavia, heat. Pair with Muir for summer." },
  { species: "lettuceLeaf", id: "lettuce-leaf-tropicana", cultivar: "Tropicana", dtm: 42, swatch: "#22c55e", notes: "Green oak/leaf. Slow bolt. 4-row." },
  { species: "lettuceLeaf", id: "lettuce-leaf-new-red-fire", cultivar: "New Red Fire", dtm: 45, swatch: "#ef4444" },
  { species: "lettuceLeaf", id: "lettuce-leaf-bergams-green", cultivar: "Bergam's Green", dtm: 50, notes: "Summer crisp leaf. Holds after rain better than oak." },
  { species: "lettuceLeaf", id: "lettuce-leaf-two-star", cultivar: "Two Star", dtm: 50 },
  { species: "spinach", id: "spinach-space", cultivar: "Space", dtm: 37, notes: "Smooth-leaf F1. Spring workhorse. 5-line Jang." },
  { species: "spinach", id: "spinach-gazelle", cultivar: "Gazelle", dtm: 30, notes: "Extra early smooth. First spring slot." },
  { species: "spinach", id: "spinach-flamingo", cultivar: "Flamingo", dtm: 40, swatch: "#fb7185", notes: "Semi-savoy. Fall and overwinter." },
  { species: "spinach", id: "spinach-regiment", cultivar: "Regiment", dtm: 37 },
  { species: "spinach", id: "spinach-acadia", cultivar: "Acadia", dtm: 42, notes: "Downy-mildew package. Late spring." },
  { species: "arugula", id: "arugula-sylvetta", cultivar: "Sylvetta", botanicalName: "Diplotaxis tenuifolia", dtm: 40, notes: "Wild rocket. Slower, more pungent, cut-and-come-again." },
  { species: "arugula", id: "arugula-slow-bolt", cultivar: "Slow Bolt", dtm: 35, notes: "Standard garden arugula selected for delayed bolt." },
  { species: "arugula", id: "arugula-wasabi", cultivar: "Wasabi", dtm: 30, notes: "Hot mustard-arugula cross. Mix ingredient, not a bunching green." },
  { species: "chard", id: "chard-fordhook-giant", cultivar: "Fordhook Giant", dtm: 55, swatch: "#166534", notes: "White-rib bulk bunches. 2-row 12 in if plants get large." },
  { species: "chard", id: "chard-peppermint", cultivar: "Peppermint", dtm: 55, swatch: "#fb7185" },
  { species: "chard", id: "chard-barese", cultivar: "Barese", dtm: 40, notes: "Baby-leaf Italian. Dense sow, 4-row 4 in for mix." },
  { species: "asianGreen", id: "mizuna-kyona", cultivar: "Kyona Mizuna", commonName: "Mizuna", botanicalName: "Brassica rapa var. nipposinica", dtm: 28, notes: "Feathery mustard. Mix and bunch. 4-row." },
  { species: "asianGreen", id: "tatsoi-koji", cultivar: "Koji Tatsoi", commonName: "Tatsoi", botanicalName: "Brassica rapa var. narinosa", dtm: 30, swatch: "#14532d" },
  { species: "asianGreen", id: "pac-choi-mei-qing-choi", cultivar: "Mei Qing Choi", commonName: "Pac choi", botanicalName: "Brassica rapa subsp. chinensis", dtm: 30, notes: "Baby pac choi. 4-row 4 in. Net vs flea beetle." },
  { species: "asianGreen", id: "pac-choi-joy-choi", cultivar: "Joy Choi", commonName: "Pac choi", dtm: 45, notes: "Full-size pac choi. 3-row 8 in." },
  { species: "asianGreen", id: "mustard-red-giant", cultivar: "Red Giant", commonName: "Mustard", botanicalName: "Brassica juncea", dtm: 40, swatch: "#9f1239" },
  { species: "asianGreen", id: "mustard-golden-frill", cultivar: "Golden Frill", commonName: "Mustard", botanicalName: "Brassica juncea", dtm: 28, swatch: "#eab308" },
  { species: "asianGreen", id: "komatsuna-summer-fest", cultivar: "Summer Fest", commonName: "Komatsuna", botanicalName: "Brassica rapa var. perviridis", dtm: 32 },
  { species: "asianGreen", id: "claytonia-miners-lettuce", cultivar: "Miner's Lettuce", commonName: "Claytonia", botanicalName: "Claytonia perfoliata", family: "Montiaceae", dtm: 40, frost: "extreme", notes: "Winter salad. Direct, 5-row. Extreme hardy." },
  { species: "asianGreen", id: "mache-vit", cultivar: "Vit", commonName: "Mâche", botanicalName: "Valerianella locusta", family: "Caprifoliaceae", dtm: 50, frost: "extreme", notes: "Corn salad. Fall sow. Dense 5-row. Slow." },
  { species: "asianGreen", id: "endive-tres-fine", cultivar: "Tres Fine Maraichere", commonName: "Endive", botanicalName: "Cichorium endivia", family: "Asteraceae", dtm: 45, notes: "Frisée. 3-row 8 in. Blanch optional." },
  { species: "asianGreen", id: "radicchio-fiero", cultivar: "Fiero", commonName: "Radicchio", botanicalName: "Cichorium intybus", family: "Asteraceae", dtm: 65, swatch: "#7f1d1d", notes: "Treviso-type. Fall crop. 3-row 10 in." },
  { species: "asianGreen", id: "sorrel-profusion", cultivar: "Profusion", commonName: "Sorrel", botanicalName: "Rumex acetosa", family: "Polygonaceae", dtm: 50, notes: "Perennial bed. 2-row. Lemon-acid leaves, high-margin bunches." },

  // —— brassicas ——
  { species: "kale", id: "kale-lacinato", cultivar: "Lacinato", botanicalName: "Brassica oleracea var. palmifolia", dtm: 62, swatch: "#14532d", notes: "Dinosaur/Tuscan. 2-row 12 in. Slowest kale, best after frost." },
  { species: "kale", id: "kale-darkibor", cultivar: "Darkibor", dtm: 55, notes: "Curly F1, darker than Winterbor. Same 2-row geometry." },
  { species: "kale", id: "kale-redbor", cultivar: "Redbor", dtm: 55, swatch: "#9f1239" },
  { species: "kale", id: "kale-white-russian", cultivar: "White Russian", dtm: 50, notes: "Siberian, tender. Faster than Red Russian, less cold-hardy." },
  { species: "kale", id: "kale-dazzling-blue", cultivar: "Dazzling Blue", dtm: 60, swatch: "#1e3a5f", notes: "Lacinato type with purple midrib. Market color." },
  { species: "broccoli", id: "broccoli-gypsy", cultivar: "Gypsy", dtm: 60, notes: "Heat-capable crown. 2-row 15 in. Spring and early summer." },
  { species: "broccoli", id: "broccoli-belstar", cultivar: "Belstar", dtm: 66, notes: "Reliable crown, good side-shoots. Spring/fall." },
  { species: "broccoli", id: "broccoli-imperial", cultivar: "Imperial", dtm: 70, notes: "Fall slot. Large dome, holds without ricing." },
  { species: "broccoli", id: "broccoli-artwork", cultivar: "Artwork", dtm: 55, notes: "Stem broccoli (Tenderstem type). Higher piece count, 2-row 12 in." },
  { species: "cabbage", id: "cabbage-tiara", cultivar: "Tiara", dtm: 45, notes: "Early mini green. 2-row 12 in. CSA favorite." },
  { species: "cabbage", id: "cabbage-farao", cultivar: "Farao", dtm: 50, notes: "Small green, excellent wrapper. 2-row 12 in." },
  { species: "cabbage", id: "cabbage-tanzanita", cultivar: "Tanzanita", dtm: 65, swatch: "#6b21a8", notes: "Red mini. Same spacing as Tiara." },
  { species: "cabbage", id: "cabbage-kaitlin", cultivar: "Kaitlin", dtm: 95, notes: "Storage green. 2-row 18 in. Cure heads, hold 32°F." },
  { species: "cabbage", id: "cabbage-adora-savoy", cultivar: "Adora Savoy", botanicalName: "Brassica oleracea var. sabauda", dtm: 70, notes: "Savoy. 2-row 15 in. Beautiful market heads." },
  { species: "cauliflower", id: "cauliflower-skywalker", cultivar: "Skywalker", dtm: 75, notes: "Self-wrapping white. Fall money crop." },
  { species: "cauliflower", id: "cauliflower-flamestar", cultivar: "Flamestar", dtm: 68, swatch: "#f97316", notes: "Orange curd. Same 2-row 18 in." },
  { species: "cauliflower", id: "cauliflower-graffiti", cultivar: "Graffiti", dtm: 80, swatch: "#7e22ce", notes: "Purple curd. Cooks to blue-green — sell raw." },
  { species: "kohlrabi", id: "kohlrabi-winner", cultivar: "Winner", dtm: 45, swatch: "#86efac" },
  { species: "kohlrabi", id: "kohlrabi-kolibri", cultivar: "Kolibri", dtm: 45, swatch: "#a21caf" },
  { species: "broccoli", id: "brussels-nautic", cultivar: "Nautic", commonName: "Brussels sprout", botanicalName: "Brassica oleracea var. gemmifera", dtm: 110, holding: 21, notes: "Mid-late Brussels. 2-row 18 in. Top plants in September." },
  { species: "broccoli", id: "brussels-dagan", cultivar: "Dagan", commonName: "Brussels sprout", botanicalName: "Brassica oleracea var. gemmifera", dtm: 100, notes: "Earlier Brussels. Same geometry as Nautic." },
  { species: "kale", id: "collard-champion", cultivar: "Champion", commonName: "Collard", botanicalName: "Brassica oleracea var. viridis", dtm: 60, notes: "Collard. 2-row 12 in. Southern bunches, frost-sweet." },
  { species: "kale", id: "collard-flash", cultivar: "Flash", commonName: "Collard", botanicalName: "Brassica oleracea var. viridis", dtm: 55 },
  { species: "broccoli", id: "rapini-sessantina", cultivar: "Sessantina Grossa", commonName: "Broccoli raab", botanicalName: "Brassica rapa subsp. ruvo", dtm: 40, notes: "Broccoli raab. Fast, 3-row 8 in. Bitter when heat-stressed." },
  { species: "cabbage", id: "chinese-cabbage-bilko", cultivar: "Bilko", commonName: "Napa cabbage", botanicalName: "Brassica rapa subsp. pekinensis", dtm: 54, notes: "Napa. 2-row 12 in. Clubroot-tolerant. Fall crop." },

  // —— roots ——
  { species: "carrot", id: "carrot-nelson", cultivar: "Nelson", dtm: 56, notes: "Early Nantes bunching. 5-line. Spring first harvest." },
  { species: "carrot", id: "carrot-mokum", cultivar: "Mokum", dtm: 54, notes: "Extra-early Nantes. Tender, not for storage." },
  { species: "carrot", id: "carrot-napoli", cultivar: "Napoli", dtm: 58, notes: "Overwinter Nantes. Sweet after frost." },
  { species: "carrot", id: "carrot-romance", cultivar: "Romance", dtm: 70, notes: "Main-season Nantes. Smooth, high pack-out." },
  { species: "carrot", id: "carrot-purple-haze", cultivar: "Purple Haze", dtm: 70, swatch: "#6b21a8", notes: "Purple skin, orange core. 5-line. Market color." },
  { species: "carrot", id: "carrot-white-satin", cultivar: "White Satin", dtm: 70, swatch: "#f5f5f4" },
  { species: "radish", id: "radish-cherry-belle", cultivar: "Cherry Belle", dtm: 24, swatch: "#ef4444" },
  { species: "radish", id: "radish-sparkler", cultivar: "Sparkler", dtm: 26, swatch: "#fca5a5" },
  { species: "radish", id: "radish-watermelon", cultivar: "Watermelon", botanicalName: "Raphanus sativus var. niger", dtm: 55, notes: "Green skin, magenta flesh. 3-row 3 in. Fall." },
  { species: "radish", id: "radish-daikon-minowase", cultivar: "Minowase Summer Cross", botanicalName: "Raphanus sativus var. longipinnatus", dtm: 55, notes: "Daikon. 3-row 4 in. Don't let it sit or pithy." },
  { species: "radish", id: "radish-nero-tondo", cultivar: "Nero Tondo", botanicalName: "Raphanus sativus var. niger", dtm: 55, swatch: "#18181b", notes: "Black Spanish. Storage radish. 3-row." },
  { species: "beet", id: "beet-red-ace", cultivar: "Red Ace", dtm: 50, notes: "The red table beet. Smooth, uniform, 4-row 3 in." },
  { species: "beet", id: "beet-touchstone-gold", cultivar: "Touchstone Gold", dtm: 55, swatch: "#f59e0b", notes: "Gold. Doesn't bleed. Same geometry as Red Ace." },
  { species: "beet", id: "beet-merlot", cultivar: "Merlot", dtm: 58, swatch: "#7f1d1d" },
  { species: "turnip", id: "turnip-hakurei", cultivar: "Hakurei", dtm: 38, notes: "White salad turnip. 4-row 3 in. The standard." },
  { species: "turnip", id: "turnip-scarlet-queen", cultivar: "Scarlet Queen", dtm: 40, swatch: "#e11d48" },
  { species: "turnip", id: "turnip-purple-top", cultivar: "Purple Top White Globe", dtm: 50, notes: "Storage turnip. Larger, 3-row 4 in." },
  { species: "turnip", id: "rutabaga-helenor", cultivar: "Helenor", commonName: "Rutabaga", botanicalName: "Brassica napus subsp. napobrassica", dtm: 90, notes: "Storage swede. 2-row 12 in. Fall only." },
  { species: "carrot", id: "parsnip-javelin", cultivar: "Javelin", commonName: "Parsnip", botanicalName: "Pastinaca sativa", dtm: 110, notes: "Parsnip. 3-row 3 in. Same seedbed discipline as carrot. Sweet after frost." },
  { species: "carrot", id: "parsnip-hollow-crown", cultivar: "Hollow Crown", commonName: "Parsnip", botanicalName: "Pastinaca sativa", dtm: 105 },
  { species: "turnip", id: "celeriac-brilliant", cultivar: "Brilliant", commonName: "Celeriac", botanicalName: "Apium graveolens var. rapaceum", dtm: 100, notes: "Celeriac. Transplant 128s, 3-row 8 in. Long season." },
  { species: "radish", id: "salsify-sandwich-island", cultivar: "Sandwich Island", commonName: "Salsify", botanicalName: "Tragopogon porrifolius", dtm: 120, notes: "Salsify. 3-row. Niche winter root." },

  // —— alliums ——
  { species: "onion", id: "onion-copra", cultivar: "Copra", dtm: 105, notes: "Long-day yellow storage. Hard, 8–10 month. 4-row 4 in." },
  { species: "onion", id: "onion-patterson", cultivar: "Patterson", dtm: 104, notes: "Replaces Copra at many farms. Long-day yellow." },
  { species: "onion", id: "onion-red-carpet", cultivar: "Red Carpet", dtm: 108, swatch: "#9f1239", notes: "Long-day red storage. Alternate to Redwing." },
  { species: "onion", id: "onion-walla-walla", cultivar: "Walla Walla", dtm: 90, notes: "Sweet long-day. Poor storage — sell fresh August–September." },
  { species: "onion", id: "onion-candy", cultivar: "Candy", dtm: 95, notes: "Intermediate-day sweet. Mid-latitudes." },
  { species: "onion", id: "onion-ailsa-craig", cultivar: "Ailsa Craig", dtm: 110, notes: "Exhibition sweet. Large bulbs, short storage." },
  { species: "scallion", id: "scallion-parade", cultivar: "Parade", notes: "The bunching onion. 4 seeds/200-cell, plant the plug." },
  { species: "scallion", id: "scallion-nabechan", cultivar: "Nabechan", notes: "Japanese bunching, sweeter, thicker. Same geometry." },
  { species: "scallion", id: "scallion-white-spear", cultivar: "White Spear" },
  { species: "scallion", id: "scallion-ishikura", cultivar: "Ishikura", dtm: 60, notes: "Long white shank. 4-row." },
  { species: "leek", id: "leek-king-richard", cultivar: "King Richard", dtm: 75, notes: "Early, long shank. Summer leek. Not for overwinter." },
  { species: "leek", id: "leek-bandit", cultivar: "Bandit", dtm: 110, frost: "extreme", notes: "Overwinter. Dark flag, stout." },
  { species: "leek", id: "leek-tadorna", cultivar: "Tadorna", dtm: 100 },
  { species: "garlic", id: "garlic-music", cultivar: "Music", notes: "Porcelain hardneck. Huge cloves, scapes in May. Fall plant." },
  { species: "garlic", id: "garlic-german-extra-hardy", cultivar: "German Extra Hardy", notes: "Rocambole/hardneck. Classic Northern storage garlic." },
  { species: "onion", id: "shallot-ambition", cultivar: "Ambition", commonName: "Shallot", botanicalName: "Allium cepa var. aggregatum", dtm: 110, notes: "Seed shallot. 4-row 4 in. Cure like onion." },

  // —— solanaceous ——
  { species: "tomatoCherry", id: "tomato-sun-peach", cultivar: "Sun Peach", dtm: 60, swatch: "#fb923c", notes: "Pink cherry, crack-resistant sister to Sun Gold. Same trellis." },
  { species: "tomatoCherry", id: "tomato-black-cherry", cultivar: "Black Cherry", dtm: 64, swatch: "#44403c" },
  { species: "tomatoCherry", id: "tomato-juliet", cultivar: "Juliet", dtm: 60, notes: "Grape. Crack-proof, high pack-out. 1-row 18 in." },
  { species: "tomatoCherry", id: "tomato-estes", cultivar: "Estes", dtm: 62, notes: "Red grape. Firm, ships. 1-row." },
  { species: "tomatoSlicer", id: "tomato-big-beef", cultivar: "Big Beef", dtm: 73, notes: "Beefsteak workhorse. 1-row 24 in." },
  { species: "tomatoSlicer", id: "tomato-celebrity", cultivar: "Celebrity", dtm: 70, notes: "Determinate-leaning. Disease package. Stake." },
  { species: "tomatoSlicer", id: "tomato-galahad", cultivar: "Galahad", dtm: 75, notes: "Late-blight resistant slicer." },
  { species: "tomatoSlicer", id: "tomato-damsel", cultivar: "Damsel", dtm: 73, swatch: "#f9a8d4", notes: "Pink slicer, blight resistance." },
  { species: "tomatoSlicer", id: "tomato-san-marzano-lungo", cultivar: "San Marzano Lungo", dtm: 80, notes: "Paste. 1-row 18 in. Sauce SKU, strip harvest." },
  { species: "tomatoSlicer", id: "tomato-amish-paste", cultivar: "Amish Paste", dtm: 80 },
  { species: "tomatoSlicer", id: "tomato-cherokee-purple", cultivar: "Cherokee Purple", dtm: 80, swatch: "#6b21a8", notes: "Heirloom, high direct price, poor shipper. 1-row 24 in." },
  { species: "tomatoSlicer", id: "tomato-green-zebra", cultivar: "Green Zebra", dtm: 75, swatch: "#65a30d" },
  { species: "tomatoSlicer", id: "tomato-early-girl", cultivar: "Early Girl", dtm: 60, notes: "First slicer of the year. 1-row 18 in." },
  { species: "tomatoSlicer", id: "tomato-new-girl", cultivar: "New Girl", dtm: 62, notes: "Improved Early Girl, better disease." },
  { species: "tomatoSlicer", id: "tomato-defiant", cultivar: "Defiant", dtm: 70, notes: "Late blight (Ph-2, Ph-3). Insurance cultivar." },
  { species: "tomatoSlicer", id: "tomato-mountain-magic", cultivar: "Mountain Magic", dtm: 66, notes: "Campari-class. Blight resistant, saladette." },
  { species: "pepper", id: "pepper-ace", cultivar: "Ace", dtm: 60, notes: "Early bell. Sets in cool. 2-row 12 in." },
  { species: "pepper", id: "pepper-olympus", cultivar: "Olympus", dtm: 72, notes: "Blocky green-to-red bell. Main season." },
  { species: "pepper", id: "pepper-goddess", cultivar: "Goddess", dtm: 65, swatch: "#fde047", notes: "Banana. High count, 2-row 12 in." },
  { species: "pepper", id: "pepper-lunchbox-orange", cultivar: "Lunchbox Orange", dtm: 80, swatch: "#f97316", notes: "Snack pepper. Pint SKU like cherry tomato." },
  { species: "pepper", id: "pepper-shishito", cultivar: "Shishito", dtm: 60, notes: "Blister-fry. 2-row. High margin pints." },
  { species: "pepper", id: "pepper-padron", cultivar: "Padron", dtm: 60, notes: "Spanish fryer. Some hot. 2-row." },
  { species: "pepper", id: "pepper-jalapeno-early", cultivar: "Early Jalapeño", dtm: 65, swatch: "#166534" },
  { species: "pepper", id: "pepper-corno-di-toro", cultivar: "Corno di Toro", dtm: 70, notes: "Bull's horn frying pepper. Alternate to Carmen." },
  { species: "pepper", id: "pepper-flavorburst", cultivar: "Flavorburst", dtm: 68, swatch: "#eab308", notes: "Yellow-orange bell, sweet." },
  { species: "pepper", id: "pepper-king-arthur", cultivar: "King Arthur", dtm: 70 },
  { species: "pepper", id: "pepper-hot-lemon", cultivar: "Hot Lemon", dtm: 70, swatch: "#facc15" },
  { species: "eggplant", id: "eggplant-nadia", cultivar: "Nadia", dtm: 67, notes: "Classic Italian. 1-row 18 in." },
  { species: "eggplant", id: "eggplant-ichiban", cultivar: "Ichiban", dtm: 58, notes: "Asian slender. Higher count, 2-row 12 in possible." },
  { species: "eggplant", id: "eggplant-fairy-tale", cultivar: "Fairy Tale", dtm: 50, swatch: "#c084fc", notes: "Mini striped. Pint SKU. 2-row 10 in." },
  { species: "pepper", id: "tomatillo-toma-verde", cultivar: "Toma Verde", commonName: "Tomatillo", botanicalName: "Physalis philadelphica", dtm: 70, notes: "Tomatillo. 1-row 24 in, needs a pollinator neighbor. Husk fruit." },
  { species: "pepper", id: "ground-cherry-cossack", cultivar: "Cossack Pineapple", commonName: "Ground cherry", botanicalName: "Physalis pruinosa", dtm: 70, notes: "Ground cherry. Pint of husk fruit. Direct price high, wholesale rare." },

  // —— cucurbits ——
  { species: "cucumber", id: "cucumber-corinto", cultivar: "Corinto", dtm: 48, notes: "Parthenocarpic slicer. Greenhouse or field. 1-row trellis." },
  { species: "cucumber", id: "cucumber-dasher-ii", cultivar: "Dasher II", dtm: 52 },
  { species: "cucumber", id: "cucumber-general-lee", cultivar: "General Lee", dtm: 55, notes: "Southern slicer, CMV. 1-row trellis." },
  { species: "cucumber", id: "cucumber-diva", cultivar: "Diva", dtm: 55, notes: "Thin-skin, burpless, parthenocarpic. Pick small." },
  { species: "cucumber", id: "cucumber-suyo-long", cultivar: "Suyo Long", dtm: 60, notes: "Ribbed Asian. Trellis. 12–15 in fruit." },
  { species: "cucumber", id: "cucumber-national-pickling", cultivar: "National Pickling", dtm: 52, notes: "Pickler. 1-row. Pick at 3–4 in." },
  { species: "zucchini", id: "zucchini-dunja", cultivar: "Dunja", dtm: 45, notes: "PM-resistant dark zucchini. 1-row 24 in." },
  { species: "zucchini", id: "zucchini-desert", cultivar: "Desert", dtm: 48 },
  { species: "zucchini", id: "zucchini-golden-delight", cultivar: "Golden Delight", dtm: 50, swatch: "#facc15" },
  { species: "zucchini", id: "squash-sunburst", cultivar: "Sunburst", commonName: "Summer squash", botanicalName: "Cucurbita pepo", dtm: 50, swatch: "#f59e0b", notes: "Scallop. Pick silver-dollar to 3 in." },
  { species: "zucchini", id: "squash-yellow-crookneck", cultivar: "Yellow Crookneck", commonName: "Summer squash", dtm: 50, swatch: "#fde047" },
  { species: "winterSquash", id: "squash-waltham", cultivar: "Waltham Butternut", botanicalName: "Cucurbita moschata", dtm: 105, notes: "Standard butternut. 1-row 24 in. Cure 10 d." },
  { species: "winterSquash", id: "squash-honeynut", cultivar: "Honeynut", dtm: 100, notes: "Personal butternut. High $/lb. Same geometry." },
  { species: "winterSquash", id: "squash-hokkaido", cultivar: "Red Kuri / Hokkaido", botanicalName: "Cucurbita maxima", dtm: 92, swatch: "#c2410c" },
  { species: "winterSquash", id: "squash-delicata", cultivar: "Delicata", botanicalName: "Cucurbita pepo", dtm: 80, notes: "Short-storage. Sell September–November. Edible skin." },
  { species: "winterSquash", id: "squash-spaghetti", cultivar: "Vegetable Spaghetti", botanicalName: "Cucurbita pepo", dtm: 90 },
  { species: "melon", id: "melon-sarahs-choice", cultivar: "Sarah's Choice", dtm: 76, notes: "Eastern muskmelon. Full slip. Plasticulture." },
  { species: "melon", id: "melon-sugar-cube", cultivar: "Sugar Cube", dtm: 80, notes: "Personal melon. High count, high direct price." },
  { species: "melon", id: "watermelon-sugar-baby", cultivar: "Sugar Baby", commonName: "Watermelon", botanicalName: "Citrullus lanatus", dtm: 76, swatch: "#14532d", notes: "Icebox watermelon. 1-row 24 in." },
  { species: "melon", id: "watermelon-blacktail-mountain", cultivar: "Blacktail Mountain", commonName: "Watermelon", botanicalName: "Citrullus lanatus", dtm: 72, notes: "Short-season icebox. Northern slot." },

  // —— legumes ——
  { species: "bean", id: "bean-jade", cultivar: "Jade", dtm: 55, notes: "Dark-green filet/snap. The market bean after Provider." },
  { species: "bean", id: "bean-maxibel", cultivar: "Maxibel", dtm: 55, notes: "Filet. Pick pencil-thin every other day." },
  { species: "bean", id: "bean-roc-dor", cultivar: "Roc d'Or", dtm: 52, swatch: "#facc15", notes: "Yellow wax. Color mix box." },
  { species: "bean", id: "bean-royal-burgundy", cultivar: "Royal Burgundy", dtm: 55, swatch: "#6b21a8" },
  { species: "bean", id: "bean-dragon-tongue", cultivar: "Dragon Tongue", dtm: 58, notes: "Flat, streaked. Direct-market novelty." },
  { species: "bean", id: "bean-fortex", cultivar: "Fortex", dtm: 60, notes: "Pole filet. Hortonova. Highest quality snap." },
  { species: "bean", id: "bean-kentucky-wonder", cultivar: "Kentucky Wonder", dtm: 65, notes: "Pole. Heirloom, string if late." },
  { species: "bean", id: "bean-edamame-beer-friend", cultivar: "Beer Friend", commonName: "Edamame", botanicalName: "Glycine max", dtm: 75, notes: "Edamame. 2-row. Strip when pods plump green." },
  { species: "pea", id: "pea-oregon-giant", cultivar: "Oregon Giant", botanicalName: "Pisum sativum var. macrocarpon", dtm: 70, notes: "Snow pea. Huge pods, Hortonova." },
  { species: "pea", id: "pea-sugar-ann", cultivar: "Sugar Ann", dtm: 52, notes: "Extra-early dwarf snap. No trellis required but yield drops." },
  { species: "pea", id: "pea-cascade-adventurer", cultivar: "Cascade Adventurer", dtm: 65, notes: "PM-resistant snap. Main trellis crop." },
  { species: "pea", id: "pea-green-arrow", cultivar: "Green Arrow", botanicalName: "Pisum sativum", dtm: 68, notes: "Shelling pea. 2-row. High shell-out." },
  { species: "pea", id: "pea-mammoth-melting", cultivar: "Mammoth Melting Sugar", botanicalName: "Pisum sativum var. macrocarpon", dtm: 70, notes: "Tall snow. Must trellis." },
  { species: "bean", id: "lima-fordhook", cultivar: "Fordhook 242", commonName: "Lima bean", botanicalName: "Phaseolus lunatus", dtm: 80, notes: "Bush lima. Warm soil only. 2-row 4 in." },

  // —— herbs ——
  { species: "basil", id: "basil-prospera", cultivar: "Prospera", dtm: 55, notes: "Downy-mildew resistant Genovese type. August insurance." },
  { species: "basil", id: "basil-eleonora", cultivar: "Eleonora", dtm: 52, notes: "DM-tolerant. Slightly more serrate leaf." },
  { species: "basil", id: "basil-siam-queen", cultivar: "Siam Queen", botanicalName: "Ocimum basilicum var. thyrsiflora", dtm: 50, swatch: "#c084fc", notes: "Thai. Anise. 3-row 8 in." },
  { species: "basil", id: "basil-purple-ruffles", cultivar: "Purple Ruffles", dtm: 55, swatch: "#6b21a8" },
  { species: "basil", id: "basil-lemon", cultivar: "Mrs Burns' Lemon", botanicalName: "Ocimum × citriodorum", dtm: 50, swatch: "#fde047" },
  { species: "cilantro", id: "cilantro-calypso", cultivar: "Calypso", dtm: 50, notes: "Slowest bolt. Summer cilantro slot." },
  { species: "cilantro", id: "cilantro-cruiser", cultivar: "Cruiser", dtm: 50, notes: "Upright, slow bolt, machine-harvestable bunches." },
  { species: "parsley", id: "parsley-giant-of-italy", cultivar: "Giant of Italy", notes: "Flat-leaf standard. 3-row 6 in. Long harvest." },
  { species: "parsley", id: "parsley-forest-green", cultivar: "Forest Green", botanicalName: "Petroselinum crispum var. crispum", notes: "Curly. Garnish bunches." },
  { species: "dill", id: "dill-bouquet", cultivar: "Bouquet", notes: "Leaf then umbel. Succession every 14 d." },
  { species: "dill", id: "dill-fernleaf", cultivar: "Fernleaf", dtm: 40, notes: "Dwarf, slow bolt. 3-row." },
  { species: "herbPerennial", id: "oregano-greek", cultivar: "Greek Oregano", commonName: "Oregano", botanicalName: "Origanum vulgare subsp. hirtum", dtm: 60, notes: "Perennial. 3-row 8 in. Don't overwater. Dry or fresh bunch." },
  { species: "herbPerennial", id: "thyme-german-winter", cultivar: "German Winter", commonName: "Thyme", botanicalName: "Thymus vulgaris", dtm: 70, notes: "Hardy thyme. 3-row. Woody, years 2–4 are the yield years." },
  { species: "herbPerennial", id: "chives-purly", cultivar: "Purly", commonName: "Chives", botanicalName: "Allium schoenoprasum", dtm: 45, notes: "Chives. 3-row. Cut 2 in above crown. Flowers are a SKU." },
  { species: "herbPerennial", id: "garlic-chives", cultivar: "Garlic Chives", commonName: "Garlic chives", botanicalName: "Allium tuberosum", dtm: 50, notes: "Flat leaf, garlic note. 3-row. Invasive seed — deadhead." },
  { species: "herbPerennial", id: "sage-common", cultivar: "Common Sage", commonName: "Sage", botanicalName: "Salvia officinalis", dtm: 70, notes: "Woody. 2-row 12 in. Year-2 yield." },
  { species: "herbPerennial", id: "shiso-aka", cultivar: "Aka Shiso", commonName: "Shiso", botanicalName: "Perilla frutescens", dtm: 50, swatch: "#9f1239", notes: "Red perilla. 3-row 8 in. Direct or transplant." },
  { species: "herbPerennial", id: "shiso-ao", cultivar: "Ao Shiso", commonName: "Shiso", botanicalName: "Perilla frutescens", dtm: 50, swatch: "#166534", notes: "Green perilla. Same geometry as Aka." },
  { species: "herbPerennial", id: "cutting-celery-afina", cultivar: "Afina", commonName: "Cutting celery", botanicalName: "Apium graveolens var. secalinum", dtm: 60, notes: "Leaf celery. 3-row 6 in. Cut-and-come-again bunches." },
  { species: "herbPerennial", id: "chervil-brussels-winter", cultivar: "Brussels Winter", commonName: "Chervil", botanicalName: "Anthriscus cerefolium", dtm: 40, notes: "Shade, cool. 4-row. Bolts in heat." },
  { species: "herbPerennial", id: "savory-summer", cultivar: "Summer Savory", commonName: "Savory", botanicalName: "Satureja hortensis", dtm: 42, notes: "Annual bean-herb. 3-row 6 in." },
  { species: "herbPerennial", id: "marjoram-sweet", cultivar: "Sweet Marjoram", commonName: "Marjoram", botanicalName: "Origanum majorana", dtm: 60, notes: "Tender perennial, grow as annual. 3-row." },
];

function expand(species: SpeciesKey, v: Variant): Crop {
  const t = S[species];
  const unitsFt = v.unitsFt ?? t.unitsFt;
  const lbsFt = v.lbsFt ?? t.lbsFt;
  return {
    id: v.id,
    commonName: v.commonName ?? t.commonName,
    cultivar: v.cultivar,
    botanicalName: v.botanicalName ?? t.botanicalName,
    family: v.family ?? t.family,
    category: t.category,
    propagation: {
      method: t.method,
      recommendedCellSize: t.cell,
      nurseryLeadDays: t.nursery,
      germinationDays: t.germDays,
      minGermTempF: t.germMin,
      optimumGermTempF: t.germOpt,
      maxGermTempF: t.germMax,
    },
    fieldGeometry: t.geom,
    timeline: {
      dtmFromField: v.dtm ?? t.dtm,
      fieldHoldingDays: v.holding ?? t.holding,
      isMulticut: t.multicut,
      regrowthDays: t.regrowth,
      maxHarvests: t.harvests,
      fallPhotoperiodMultiplier: t.fall,
      frostHardiness: v.frost ?? t.frost,
    },
    yieldAndRevenue: {
      salesUnit: t.unit,
      unitsPerBedFoot: unitsFt,
      avgWeightPerUnitLbs: t.ozUnit,
      targetYieldLbsPerBedFoot: lbsFt,
      standardCullRate: t.cull,
      targetWholesalePriceUsd: v.whole ?? t.whole,
      targetDirectPriceUsd: v.direct ?? t.direct,
    },
    irrigationProfile: t.irr,
    soilExtractionProfile: {
      fertilityDemand: t.demand,
      nRemovalLbsPer100BedFt: t.n,
      pRemovalLbsPer100BedFt: t.p,
      kRemovalLbsPer100BedFt: t.k,
    },
    successionIntervalDays: t.interval,
    maxSuccessions: t.maxSucc,
    companions: t.companions,
    avoid: t.avoid,
    notes: v.notes ?? t.notes,
    swatch: v.swatch ?? t.swatch,
  };
}

export const CULTIVAR_DATABASE: Crop[] = VARIANTS.map((row) => expand(row.species, row));

function storageFor(crop: Crop, species: SpeciesKey): CropPostHarvestSpec {
  return { crop_id: crop.id, ...S[species].store };
}

function isMain(): boolean {
  const self = fileURLToPath(import.meta.url);
  const invoked = process.argv[1] ? join(process.argv[1]) : "";
  return self === invoked || invoked.endsWith("seed-cultivars.ts");
}

export function seedCultivars(): { written: number; preserved: number; specs: number; totalOnDisk: number } {
  if (!existsSync(cropDir)) mkdirSync(cropDir, { recursive: true });

  const ids = new Set<string>();
  for (const id of PRESERVE_IDS) ids.add(id);
  let written = 0;
  let preserved = 0;
  const newSpecs: CropPostHarvestSpec[] = [];

  for (const row of VARIANTS) {
    if (ids.has(row.id)) throw new Error(`Duplicate cultivar id: ${row.id}`);
    ids.add(row.id);
    const crop = expand(row.species, row);
    const file = join(cropDir, `${crop.id}.json`);
    if (PRESERVE.has(crop.id) && existsSync(file)) {
      preserved += 1;
      continue;
    }
    writeFileSync(file, `${JSON.stringify(crop, null, 2)}\n`, "utf8");
    written += 1;
    newSpecs.push(storageFor(crop, row.species));
  }

  const existing: CropPostHarvestSpec[] = existsSync(storagePath)
    ? (JSON.parse(readFileSync(storagePath, "utf8")) as CropPostHarvestSpec[])
    : [];
  const specById = new Map(existing.map((s) => [s.crop_id, s]));
  for (const spec of newSpecs) {
    if (!specById.has(spec.crop_id)) specById.set(spec.crop_id, spec);
  }

  const onDisk = readdirSync(cropDir).filter((f) => f.endsWith(".json"));
  for (const file of onDisk) {
    const crop = JSON.parse(readFileSync(join(cropDir, file), "utf8")) as Crop;
    if (!specById.has(crop.id)) {
      const row = VARIANTS.find((v) => v.id === crop.id);
      const species = row?.species ?? "lettuceHead";
      specById.set(crop.id, storageFor(crop, species));
    }
  }

  const specs = [...specById.values()].sort((a, b) => a.crop_id.localeCompare(b.crop_id));
  writeFileSync(storagePath, `${JSON.stringify(specs, null, 2)}\n`, "utf8");

  return { written, preserved, specs: specs.length, totalOnDisk: onDisk.length };
}

if (isMain()) {
  const result = seedCultivars();
  console.log(
    `Seeded ${result.written} new cultivar files (${result.preserved} preserved). Catalog on disk: ${result.totalOnDisk}. Storage specs: ${result.specs}.`,
  );
}
