/**
 * Phase 2 — specialty cut flowers.
 * Writes camelCase Crop JSON with flowerSpecifics. Never overwrites vegetable files.
 *
 * Run: node --experimental-strip-types scripts/seed-flowers.ts
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type {
  Crop,
  CutFlowerSpecifics,
  FlowerHarvestStage,
  FlowerUse,
  FrostHardiness,
  PostHarvestPulse,
} from "../src/types/crop.ts";
import type { CropPostHarvestSpec } from "../src/types/economics.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const cropDir = join(root, "src/data/crops");
const storagePath = join(root, "src/data/economics/storageSpecs.json");

type Geom = Crop["fieldGeometry"];
type Irr = Crop["irrigationProfile"];
type Store = Omit<CropPostHarvestSpec, "crop_id">;

function geom(rows: 1 | 2 | 3 | 4 | 5 | 6, inRow: number): Geom {
  const plants = Math.round(rows * (12 / inRow) * 100) / 100;
  return {
    standardBedWidthIn: 30,
    rowsPerBed: rows,
    inRowSpacingIn: inRow,
    seedSpacingIn: Math.min(2, Math.max(0.5, inRow / 4)),
    plantsPerLinearFoot: plants,
  };
}

function irr(weekIn: number, lines: 1 | 2 | 3 | 4 = 2): Irr {
  return { linesPerBed: lines, emitterSpacingIn: 8, emitterGph: 0.42, weeklyWaterRequirementIn: weekIn };
}

const Z2: Store = {
  storage_zone: "zone-2-cool-humid",
  optimal_temp_f: 36,
  min_safe_temp_f: 34,
  max_temp_f: 40,
  optimal_rh_pct: 80,
  shelf_life_days: 7,
  cooling_method: "forced-air",
  respiration_rate_rating: "moderate",
  sensible_heat_btu_per_lb: 0.9,
  totes_per_100_lbs: 6,
  harvest_hours_per_100_bed_ft: 3.5,
};

const Z_TENDER: Store = {
  ...Z2,
  optimal_temp_f: 50,
  min_safe_temp_f: 45,
  max_temp_f: 55,
  cooling_method: "room-cooling",
  harvest_hours_per_100_bed_ft: 3.2,
};

function net(
  required: boolean,
  layers: 1 | 2,
  mesh: 6 | 8,
  first: number,
  second: number | null,
): CutFlowerSpecifics["supportNetting"] {
  return {
    required,
    layers,
    meshSizeIn: mesh,
    firstLayerHeightIn: first,
    secondLayerHeightIn: second,
  };
}

function pinch(
  required: boolean,
  height: number,
  nodes: number,
  penalty: number,
): CutFlowerSpecifics["pinching"] {
  return {
    required,
    pinchAtHeightIn: height,
    leaveNodeCount: nodes,
    dtmPenaltyDays: penalty,
  };
}

function harvest(
  stage: FlowerHarvestStage,
  freq: number,
  perPlant: number,
  perFt: number,
  pulse: PostHarvestPulse,
  vase: number,
): CutFlowerSpecifics["harvestProtocol"] {
  return {
    stage,
    cutFrequencyDays: freq,
    stemsPerPlant: perPlant,
    stemsPerLinearBedFoot: perFt,
    recommendedPulse: pulse,
    vaseLifeDays: vase,
  };
}

type SpeciesKey =
  | "zinniaGiant"
  | "zinniaBranch"
  | "sunflowerProcut"
  | "sunflowerBranch"
  | "snapGroup1"
  | "snapGroup3"
  | "lisianthus"
  | "dahlia"
  | "cosmos"
  | "scabiosa"
  | "stock"
  | "celosia"
  | "statice"
  | "gomphrena"
  | "ammi"
  | "bupleurum"
  | "feverfew"
  | "yarrow"
  | "nigella"
  | "craspedia"
  | "strawflower"
  | "larkspur"
  | "bells"
  | "phlox"
  | "dianthus"
  | "rudbeckia"
  | "amaranthus"
  | "millet"
  | "eucalyptus"
  | "dustyMiller"
  | "sweetPea"
  | "ranunculus";

type Template = {
  commonName: string;
  botanicalName: string;
  family: string;
  geom: Geom;
  irr: Irr;
  dtm: number;
  holding: number;
  harvests: number;
  frost: FrostHardiness;
  nursery: number;
  cell: 72 | 128 | 200 | 288 | null;
  method: Crop["propagation"]["method"];
  germDays: number;
  germMin: number;
  germOpt: number;
  germMax: number;
  unitsFt: number;
  ozUnit: number;
  lbsFt: number;
  cull: number;
  whole: number;
  direct: number;
  n: number;
  p: number;
  k: number;
  interval: number;
  maxSucc: number;
  notes: string;
  swatch: string;
  store: Store;
  flower: Omit<CutFlowerSpecifics, "primaryUse"> & { primaryUse: FlowerUse };
};

const NONE_NET = net(false, 1, 6, 0, null);
const NONE_PINCH = pinch(false, 0, 0, 0);

const S: Record<SpeciesKey, Template> = {
  zinniaGiant: {
    commonName: "Zinnia",
    botanicalName: "Zinnia elegans",
    family: "Asteraceae",
    geom: geom(3, 9),
    irr: irr(1.1),
    dtm: 75,
    holding: 21,
    harvests: 8,
    frost: "tender",
    nursery: 21,
    cell: 72,
    method: "both",
    germDays: 5,
    germMin: 70,
    germOpt: 80,
    germMax: 90,
    unitsFt: 8,
    ozUnit: 0.06,
    lbsFt: 0.48,
    cull: 0.12,
    whole: 0.55,
    direct: 1.1,
    n: 1.6,
    p: 0.4,
    k: 2.2,
    interval: 14,
    maxSucc: 3,
    notes: "Pinch at 8–12 in. Hortonova 8 in mesh at 18 in. Cut fully open — zinnias do not continue to open in the vase. No cold box below 45°F.",
    swatch: "#e11d48",
    store: { ...Z_TENDER, shelf_life_days: 7 },
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 24,
      supportNetting: net(true, 1, 8, 18, null),
      pinching: pinch(true, 10, 4, 12),
      harvestProtocol: harvest("fully-open", 3, 6, 8, "plain-cold-water", 7),
    },
  },
  zinniaBranch: {
    commonName: "Zinnia",
    botanicalName: "Zinnia elegans",
    family: "Asteraceae",
    geom: geom(4, 6),
    irr: irr(1.0),
    dtm: 65,
    holding: 18,
    harvests: 8,
    frost: "tender",
    nursery: 21,
    cell: 72,
    method: "both",
    germDays: 5,
    germMin: 70,
    germOpt: 80,
    germMax: 90,
    unitsFt: 10,
    ozUnit: 0.04,
    lbsFt: 0.4,
    cull: 0.12,
    whole: 0.4,
    direct: 0.85,
    n: 1.5,
    p: 0.35,
    k: 2,
    interval: 14,
    maxSucc: 3,
    notes: "Oklahoma / Queen class. Tighter spacing, smaller bloom, more stems. Same pinch and no-chill rule as Benary's.",
    swatch: "#fb7185",
    store: { ...Z_TENDER, shelf_life_days: 6 },
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 18,
      supportNetting: net(true, 1, 8, 16, null),
      pinching: pinch(true, 8, 4, 10),
      harvestProtocol: harvest("fully-open", 3, 5, 10, "plain-cold-water", 6),
    },
  },
  sunflowerProcut: {
    commonName: "Sunflower",
    botanicalName: "Helianthus annuus",
    family: "Asteraceae",
    geom: geom(2, 6),
    irr: irr(1.3),
    dtm: 55,
    holding: 5,
    harvests: 1,
    frost: "tender",
    nursery: 14,
    cell: 72,
    method: "both",
    germDays: 5,
    germMin: 60,
    germOpt: 75,
    germMax: 90,
    unitsFt: 4,
    ozUnit: 0.18,
    lbsFt: 0.72,
    cull: 0.1,
    whole: 1.1,
    direct: 2,
    n: 2,
    p: 0.5,
    k: 2.8,
    interval: 10,
    maxSucc: 6,
    notes: "Single-stem ProCut. Do not pinch. Direct-sow or 2-week 72s. Cut when petals just lift off the disk.",
    swatch: "#f59e0b",
    store: { ...Z2, shelf_life_days: 8, harvest_hours_per_100_bed_ft: 2.2 },
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 30,
      supportNetting: NONE_NET,
      pinching: NONE_PINCH,
      harvestProtocol: harvest("cracked-bud", 0, 1, 4, "citric-acid-hydration", 8),
    },
  },
  sunflowerBranch: {
    commonName: "Sunflower",
    botanicalName: "Helianthus annuus",
    family: "Asteraceae",
    geom: geom(2, 12),
    irr: irr(1.2),
    dtm: 70,
    holding: 14,
    harvests: 5,
    frost: "tender",
    nursery: 14,
    cell: 72,
    method: "both",
    germDays: 5,
    germMin: 60,
    germOpt: 75,
    germMax: 90,
    unitsFt: 5,
    ozUnit: 0.1,
    lbsFt: 0.5,
    cull: 0.12,
    whole: 0.85,
    direct: 1.6,
    n: 1.8,
    p: 0.45,
    k: 2.4,
    interval: 14,
    maxSucc: 3,
    notes: "Branching. Pinch above 2nd set of leaves. Teddy Bear / Autumn Beauty class.",
    swatch: "#d97706",
    store: Z2,
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 24,
      supportNetting: net(true, 1, 8, 18, null),
      pinching: pinch(true, 8, 2, 12),
      harvestProtocol: harvest("cracked-bud", 4, 5, 5, "citric-acid-hydration", 7),
    },
  },
  snapGroup1: {
    commonName: "Snapdragon",
    botanicalName: "Antirrhinum majus",
    family: "Plantaginaceae",
    geom: geom(4, 6),
    irr: irr(1.0),
    dtm: 85,
    holding: 14,
    harvests: 4,
    frost: "moderate",
    nursery: 42,
    cell: 128,
    method: "transplant",
    germDays: 8,
    germMin: 60,
    germOpt: 70,
    germMax: 80,
    unitsFt: 8,
    ozUnit: 0.05,
    lbsFt: 0.4,
    cull: 0.1,
    whole: 0.7,
    direct: 1.4,
    n: 1.8,
    p: 0.4,
    k: 2.4,
    interval: 21,
    maxSucc: 2,
    notes: "Group 1 (Potomac). Do not pinch. Two Hortonova layers at 12 and 24 in. Cut when ⅓–½ florets open.",
    swatch: "#f43f5e",
    store: { ...Z2, shelf_life_days: 8 },
    flower: {
      primaryUse: "spike",
      targetStemLengthIn: 30,
      supportNetting: net(true, 2, 6, 12, 24),
      pinching: NONE_PINCH,
      harvestProtocol: harvest("one-half-open", 5, 3, 8, "citric-acid-hydration", 8),
    },
  },
  snapGroup3: {
    commonName: "Snapdragon",
    botanicalName: "Antirrhinum majus",
    family: "Plantaginaceae",
    geom: geom(4, 6),
    irr: irr(1.0),
    dtm: 80,
    holding: 16,
    harvests: 5,
    frost: "moderate",
    nursery: 35,
    cell: 128,
    method: "transplant",
    germDays: 8,
    germMin: 60,
    germOpt: 70,
    germMax: 80,
    unitsFt: 9,
    ozUnit: 0.045,
    lbsFt: 0.4,
    cull: 0.1,
    whole: 0.6,
    direct: 1.25,
    n: 1.7,
    p: 0.4,
    k: 2.2,
    interval: 18,
    maxSucc: 3,
    notes: "Group 3 (Rocket). Pinch once. Heat-capable. Same 2-layer net as Potomac.",
    swatch: "#fb7185",
    store: Z2,
    flower: {
      primaryUse: "spike",
      targetStemLengthIn: 24,
      supportNetting: net(true, 2, 6, 12, 24),
      pinching: pinch(true, 6, 3, 10),
      harvestProtocol: harvest("one-half-open", 4, 4, 9, "citric-acid-hydration", 7),
    },
  },
  lisianthus: {
    commonName: "Lisianthus",
    botanicalName: "Eustoma grandiflorum",
    family: "Gentianaceae",
    geom: geom(4, 6),
    irr: irr(1.0),
    dtm: 110,
    holding: 18,
    harvests: 4,
    frost: "tender",
    nursery: 80,
    cell: 128,
    method: "transplant",
    germDays: 14,
    germMin: 68,
    germOpt: 75,
    germMax: 80,
    unitsFt: 7,
    ozUnit: 0.05,
    lbsFt: 0.35,
    cull: 0.12,
    whole: 1.25,
    direct: 2.25,
    n: 1.6,
    p: 0.4,
    k: 2.2,
    interval: 0,
    maxSucc: 1,
    notes: "10–12 week 128s. Do not bury the crown. One Hortonova layer. Cut at marshmallow — buds finish in the vase.",
    swatch: "#c084fc",
    store: { ...Z2, shelf_life_days: 12 },
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 24,
      supportNetting: net(true, 1, 6, 14, null),
      pinching: pinch(true, 6, 3, 14),
      harvestProtocol: harvest("marshmallow", 4, 4, 7, "chrysal-holding-soln", 12),
    },
  },
  dahlia: {
    commonName: "Dahlia",
    botanicalName: "Dahlia × hortensis",
    family: "Asteraceae",
    geom: geom(2, 18),
    irr: irr(1.2),
    dtm: 90,
    holding: 35,
    harvests: 12,
    frost: "tender",
    nursery: 21,
    cell: 72,
    method: "transplant",
    germDays: 7,
    germMin: 60,
    germOpt: 70,
    germMax: 80,
    unitsFt: 8,
    ozUnit: 0.12,
    lbsFt: 0.96,
    cull: 0.15,
    whole: 1.75,
    direct: 3,
    n: 2.2,
    p: 0.55,
    k: 3,
    interval: 0,
    maxSucc: 1,
    notes: "Tuber or cutting. Pinch above 3rd leaf pair. Two Hortonova layers. Cut ½ open. Sear stems 10 s in 180°F water.",
    swatch: "#fecdd3",
    store: { ...Z2, shelf_life_days: 5, harvest_hours_per_100_bed_ft: 4.5 },
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 24,
      supportNetting: net(true, 2, 6, 12, 24),
      pinching: pinch(true, 8, 3, 14),
      harvestProtocol: harvest("one-half-open", 2, 10, 8, "hot-water-sear", 5),
    },
  },
  cosmos: {
    commonName: "Cosmos",
    botanicalName: "Cosmos bipinnatus",
    family: "Asteraceae",
    geom: geom(3, 9),
    irr: irr(0.9),
    dtm: 70,
    holding: 21,
    harvests: 10,
    frost: "tender",
    nursery: 21,
    cell: 72,
    method: "both",
    germDays: 5,
    germMin: 65,
    germOpt: 75,
    germMax: 85,
    unitsFt: 10,
    ozUnit: 0.03,
    lbsFt: 0.3,
    cull: 0.15,
    whole: 0.4,
    direct: 0.85,
    n: 1.2,
    p: 0.3,
    k: 1.8,
    interval: 21,
    maxSucc: 2,
    notes: "Pinch. One net layer. Cut when petals are just unfurling. Airy mixer, not a cold-box crop below 40°F.",
    swatch: "#fda4af",
    store: { ...Z_TENDER, shelf_life_days: 6 },
    flower: {
      primaryUse: "airy-texture",
      targetStemLengthIn: 22,
      supportNetting: net(true, 1, 8, 18, null),
      pinching: pinch(true, 8, 3, 10),
      harvestProtocol: harvest("one-half-open", 3, 8, 10, "plain-cold-water", 6),
    },
  },
  scabiosa: {
    commonName: "Scabiosa",
    botanicalName: "Scabiosa atropurpurea",
    family: "Caprifoliaceae",
    geom: geom(3, 9),
    irr: irr(1.0),
    dtm: 90,
    holding: 28,
    harvests: 10,
    frost: "moderate",
    nursery: 28,
    cell: 128,
    method: "transplant",
    germDays: 10,
    germMin: 60,
    germOpt: 70,
    germMax: 78,
    unitsFt: 8,
    ozUnit: 0.04,
    lbsFt: 0.32,
    cull: 0.12,
    whole: 0.65,
    direct: 1.25,
    n: 1.4,
    p: 0.35,
    k: 1.9,
    interval: 21,
    maxSucc: 2,
    notes: "Cut at marshmallow. Black Knight stains water — recut underwater. Net once.",
    swatch: "#3f3f46",
    store: Z2,
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 20,
      supportNetting: net(true, 1, 6, 14, null),
      pinching: pinch(true, 6, 3, 8),
      harvestProtocol: harvest("marshmallow", 3, 8, 8, "citric-acid-hydration", 8),
    },
  },
  stock: {
    commonName: "Stock",
    botanicalName: "Matthiola incana",
    family: "Brassicaceae",
    geom: geom(4, 6),
    irr: irr(1.0),
    dtm: 80,
    holding: 10,
    harvests: 1,
    frost: "hardy",
    nursery: 35,
    cell: 128,
    method: "transplant",
    germDays: 7,
    germMin: 55,
    germOpt: 65,
    germMax: 75,
    unitsFt: 8,
    ozUnit: 0.06,
    lbsFt: 0.48,
    cull: 0.12,
    whole: 0.8,
    direct: 1.5,
    n: 1.5,
    p: 0.4,
    k: 2,
    interval: 14,
    maxSucc: 2,
    notes: "Selectable Katz: dark seed = double. Cool crop. Cut when 3–5 florets open. Citric pulse.",
    swatch: "#f5d0fe",
    store: { ...Z2, shelf_life_days: 6 },
    flower: {
      primaryUse: "spike",
      targetStemLengthIn: 22,
      supportNetting: net(true, 1, 6, 12, null),
      pinching: NONE_PINCH,
      harvestProtocol: harvest("one-half-open", 0, 1, 8, "citric-acid-hydration", 6),
    },
  },
  celosia: {
    commonName: "Celosia",
    botanicalName: "Celosia argentea",
    family: "Amaranthaceae",
    geom: geom(3, 9),
    irr: irr(1.0),
    dtm: 80,
    holding: 21,
    harvests: 6,
    frost: "tender",
    nursery: 28,
    cell: 72,
    method: "transplant",
    germDays: 8,
    germMin: 70,
    germOpt: 80,
    germMax: 90,
    unitsFt: 6,
    ozUnit: 0.07,
    lbsFt: 0.42,
    cull: 0.1,
    whole: 0.7,
    direct: 1.35,
    n: 1.5,
    p: 0.35,
    k: 2.1,
    interval: 21,
    maxSucc: 2,
    notes: "Crested (Chief) or wheat (Celway). No chill below 45°F. Harvest fully developed — they do not open further.",
    swatch: "#ea580c",
    store: { ...Z_TENDER, shelf_life_days: 10 },
    flower: {
      primaryUse: "spike",
      targetStemLengthIn: 22,
      supportNetting: net(true, 1, 8, 16, null),
      pinching: pinch(true, 8, 3, 10),
      harvestProtocol: harvest("fully-open", 4, 5, 6, "plain-cold-water", 10),
    },
  },
  statice: {
    commonName: "Statice",
    botanicalName: "Limonium sinuatum",
    family: "Plumbaginaceae",
    geom: geom(3, 9),
    irr: irr(0.9),
    dtm: 95,
    holding: 21,
    harvests: 6,
    frost: "moderate",
    nursery: 35,
    cell: 128,
    method: "transplant",
    germDays: 10,
    germMin: 60,
    germOpt: 70,
    germMax: 80,
    unitsFt: 8,
    ozUnit: 0.04,
    lbsFt: 0.32,
    cull: 0.1,
    whole: 0.45,
    direct: 0.9,
    n: 1.2,
    p: 0.3,
    k: 1.7,
    interval: 0,
    maxSucc: 1,
    notes: "QIS series. Cut when 80% of florets are colored. Dries. Filler workhorse.",
    swatch: "#e4e4e7",
    store: { ...Z2, shelf_life_days: 14 },
    flower: {
      primaryUse: "filler",
      targetStemLengthIn: 20,
      supportNetting: NONE_NET,
      pinching: NONE_PINCH,
      harvestProtocol: harvest("fully-open", 5, 6, 8, "plain-cold-water", 14),
    },
  },
  gomphrena: {
    commonName: "Gomphrena",
    botanicalName: "Gomphrena globosa",
    family: "Amaranthaceae",
    geom: geom(3, 6),
    irr: irr(0.9),
    dtm: 80,
    holding: 28,
    harvests: 8,
    frost: "tender",
    nursery: 28,
    cell: 72,
    method: "transplant",
    germDays: 8,
    germMin: 70,
    germOpt: 80,
    germMax: 90,
    unitsFt: 12,
    ozUnit: 0.02,
    lbsFt: 0.24,
    cull: 0.08,
    whole: 0.25,
    direct: 0.55,
    n: 1,
    p: 0.25,
    k: 1.5,
    interval: 21,
    maxSucc: 2,
    notes: "QIS. Cut when heads are fully colored. Dries. Heat-proof filler.",
    swatch: "#be123c",
    store: { ...Z_TENDER, shelf_life_days: 14 },
    flower: {
      primaryUse: "filler",
      targetStemLengthIn: 16,
      supportNetting: NONE_NET,
      pinching: pinch(true, 6, 3, 8),
      harvestProtocol: harvest("fully-open", 4, 10, 12, "plain-cold-water", 14),
    },
  },
  ammi: {
    commonName: "Ammi",
    botanicalName: "Ammi visnaga",
    family: "Apiaceae",
    geom: geom(3, 6),
    irr: irr(0.9),
    dtm: 75,
    holding: 14,
    harvests: 4,
    frost: "moderate",
    nursery: 28,
    cell: 128,
    method: "both",
    germDays: 12,
    germMin: 55,
    germOpt: 65,
    germMax: 75,
    unitsFt: 8,
    ozUnit: 0.03,
    lbsFt: 0.24,
    cull: 0.12,
    whole: 0.5,
    direct: 1,
    n: 1.1,
    p: 0.3,
    k: 1.6,
    interval: 21,
    maxSucc: 2,
    notes: "Green Mist. Cut when umbels are 70% open. Soft filler. Direct or 128s.",
    swatch: "#86efac",
    store: Z2,
    flower: {
      primaryUse: "filler",
      targetStemLengthIn: 22,
      supportNetting: net(true, 1, 8, 16, null),
      pinching: NONE_PINCH,
      harvestProtocol: harvest("one-half-open", 4, 5, 8, "citric-acid-hydration", 7),
    },
  },
  bupleurum: {
    commonName: "Bupleurum",
    botanicalName: "Bupleurum rotundifolium",
    family: "Apiaceae",
    geom: geom(3, 6),
    irr: irr(0.85),
    dtm: 70,
    holding: 12,
    harvests: 3,
    frost: "moderate",
    nursery: 28,
    cell: 128,
    method: "both",
    germDays: 10,
    germMin: 55,
    germOpt: 65,
    germMax: 75,
    unitsFt: 7,
    ozUnit: 0.03,
    lbsFt: 0.21,
    cull: 0.1,
    whole: 0.55,
    direct: 1.1,
    n: 1,
    p: 0.25,
    k: 1.5,
    interval: 21,
    maxSucc: 2,
    notes: "Griffithii. Chartreuse umbel filler. Cut as flowers open. Cool-season.",
    swatch: "#a3e635",
    store: Z2,
    flower: {
      primaryUse: "filler",
      targetStemLengthIn: 20,
      supportNetting: NONE_NET,
      pinching: NONE_PINCH,
      harvestProtocol: harvest("one-half-open", 5, 4, 7, "plain-cold-water", 8),
    },
  },
  feverfew: {
    commonName: "Feverfew",
    botanicalName: "Tanacetum parthenium",
    family: "Asteraceae",
    geom: geom(3, 9),
    irr: irr(0.9),
    dtm: 85,
    holding: 21,
    harvests: 6,
    frost: "hardy",
    nursery: 35,
    cell: 128,
    method: "transplant",
    germDays: 10,
    germMin: 60,
    germOpt: 70,
    germMax: 78,
    unitsFt: 9,
    ozUnit: 0.03,
    lbsFt: 0.27,
    cull: 0.1,
    whole: 0.45,
    direct: 0.9,
    n: 1.2,
    p: 0.3,
    k: 1.7,
    interval: 0,
    maxSucc: 1,
    notes: "Vegmo Snowball. Cut when 50% of buttons are open. Perennial treated as hardy annual.",
    swatch: "#fafafa",
    store: Z2,
    flower: {
      primaryUse: "filler",
      targetStemLengthIn: 18,
      supportNetting: net(true, 1, 8, 14, null),
      pinching: pinch(true, 6, 3, 8),
      harvestProtocol: harvest("one-half-open", 4, 8, 9, "plain-cold-water", 8),
    },
  },
  yarrow: {
    commonName: "Yarrow",
    botanicalName: "Achillea millefolium",
    family: "Asteraceae",
    geom: geom(3, 12),
    irr: irr(0.8),
    dtm: 90,
    holding: 21,
    harvests: 5,
    frost: "hardy",
    nursery: 42,
    cell: 128,
    method: "transplant",
    germDays: 12,
    germMin: 60,
    germOpt: 70,
    germMax: 78,
    unitsFt: 5,
    ozUnit: 0.05,
    lbsFt: 0.25,
    cull: 0.1,
    whole: 0.6,
    direct: 1.2,
    n: 1.1,
    p: 0.3,
    k: 1.8,
    interval: 0,
    maxSucc: 1,
    notes: "Summer Pastels. Cut when umbel is 80% colored. Drought-lean. Dries.",
    swatch: "#fde68a",
    store: { ...Z2, shelf_life_days: 10 },
    flower: {
      primaryUse: "filler",
      targetStemLengthIn: 20,
      supportNetting: NONE_NET,
      pinching: NONE_PINCH,
      harvestProtocol: harvest("fully-open", 5, 6, 5, "plain-cold-water", 10),
    },
  },
  nigella: {
    commonName: "Nigella",
    botanicalName: "Nigella damascena",
    family: "Ranunculaceae",
    geom: geom(4, 4),
    irr: irr(0.85),
    dtm: 70,
    holding: 14,
    harvests: 3,
    frost: "hardy",
    nursery: 0,
    cell: null,
    method: "direct-seed",
    germDays: 10,
    germMin: 50,
    germOpt: 60,
    germMax: 70,
    unitsFt: 10,
    ozUnit: 0.02,
    lbsFt: 0.2,
    cull: 0.12,
    whole: 0.35,
    direct: 0.75,
    n: 0.9,
    p: 0.2,
    k: 1.3,
    interval: 14,
    maxSucc: 3,
    notes: "Miss Jekyll. Direct-sow. Cut flowers ½ open or pods green. Airy. Hates transplanting.",
    swatch: "#93c5fd",
    store: Z2,
    flower: {
      primaryUse: "airy-texture",
      targetStemLengthIn: 16,
      supportNetting: NONE_NET,
      pinching: NONE_PINCH,
      harvestProtocol: harvest("one-half-open", 4, 3, 10, "plain-cold-water", 7),
    },
  },
  craspedia: {
    commonName: "Craspedia",
    botanicalName: "Craspedia globosa",
    family: "Asteraceae",
    geom: geom(3, 6),
    irr: irr(0.85),
    dtm: 95,
    holding: 21,
    harvests: 6,
    frost: "tender",
    nursery: 42,
    cell: 128,
    method: "transplant",
    germDays: 12,
    germMin: 65,
    germOpt: 75,
    germMax: 85,
    unitsFt: 8,
    ozUnit: 0.02,
    lbsFt: 0.16,
    cull: 0.08,
    whole: 0.4,
    direct: 0.8,
    n: 1,
    p: 0.25,
    k: 1.4,
    interval: 0,
    maxSucc: 1,
    notes: "Billy buttons. Cut when balls are fully colored. Dries. Golf Beauty.",
    swatch: "#facc15",
    store: { ...Z2, shelf_life_days: 14 },
    flower: {
      primaryUse: "filler",
      targetStemLengthIn: 18,
      supportNetting: NONE_NET,
      pinching: NONE_PINCH,
      harvestProtocol: harvest("fully-open", 4, 6, 8, "plain-cold-water", 14),
    },
  },
  strawflower: {
    commonName: "Strawflower",
    botanicalName: "Xerochrysum bracteatum",
    family: "Asteraceae",
    geom: geom(3, 9),
    irr: irr(0.9),
    dtm: 85,
    holding: 21,
    harvests: 8,
    frost: "tender",
    nursery: 28,
    cell: 72,
    method: "transplant",
    germDays: 8,
    germMin: 65,
    germOpt: 75,
    germMax: 85,
    unitsFt: 8,
    ozUnit: 0.03,
    lbsFt: 0.24,
    cull: 0.1,
    whole: 0.4,
    direct: 0.8,
    n: 1.1,
    p: 0.3,
    k: 1.6,
    interval: 21,
    maxSucc: 2,
    notes: "Cut when bracts are colored but center still tight. Dries hanging. Swiss Giants.",
    swatch: "#fdba74",
    store: { ...Z_TENDER, shelf_life_days: 21 },
    flower: {
      primaryUse: "filler",
      targetStemLengthIn: 18,
      supportNetting: net(true, 1, 8, 16, null),
      pinching: pinch(true, 8, 3, 8),
      harvestProtocol: harvest("cracked-bud", 4, 7, 8, "plain-cold-water", 21),
    },
  },
  larkspur: {
    commonName: "Larkspur",
    botanicalName: "Consolida ajacis",
    family: "Ranunculaceae",
    geom: geom(3, 6),
    irr: irr(1.0),
    dtm: 90,
    holding: 10,
    harvests: 1,
    frost: "hardy",
    nursery: 0,
    cell: null,
    method: "direct-seed",
    germDays: 14,
    germMin: 50,
    germOpt: 58,
    germMax: 68,
    unitsFt: 6,
    ozUnit: 0.05,
    lbsFt: 0.3,
    cull: 0.12,
    whole: 0.7,
    direct: 1.35,
    n: 1.4,
    p: 0.35,
    k: 2,
    interval: 14,
    maxSucc: 2,
    notes: "Giant Imperial. Fall-sow or pre-chill seed. Two net layers. Cut when ⅓ florets open.",
    swatch: "#818cf8",
    store: Z2,
    flower: {
      primaryUse: "spike",
      targetStemLengthIn: 28,
      supportNetting: net(true, 2, 6, 12, 24),
      pinching: NONE_PINCH,
      harvestProtocol: harvest("one-half-open", 0, 1, 6, "citric-acid-hydration", 7),
    },
  },
  bells: {
    commonName: "Bells of Ireland",
    botanicalName: "Moluccella laevis",
    family: "Lamiaceae",
    geom: geom(3, 9),
    irr: irr(1.0),
    dtm: 90,
    holding: 14,
    harvests: 2,
    frost: "tender",
    nursery: 35,
    cell: 128,
    method: "both",
    germDays: 12,
    germMin: 55,
    germOpt: 65,
    germMax: 75,
    unitsFt: 5,
    ozUnit: 0.06,
    lbsFt: 0.3,
    cull: 0.12,
    whole: 0.75,
    direct: 1.4,
    n: 1.3,
    p: 0.3,
    k: 1.8,
    interval: 0,
    maxSucc: 1,
    notes: "Pre-chill seed 5 d. Cut when bells are developed, flowers still small. Spike + filler.",
    swatch: "#4ade80",
    store: Z2,
    flower: {
      primaryUse: "spike",
      targetStemLengthIn: 24,
      supportNetting: net(true, 1, 8, 16, null),
      pinching: NONE_PINCH,
      harvestProtocol: harvest("fully-open", 5, 3, 5, "plain-cold-water", 8),
    },
  },
  phlox: {
    commonName: "Annual phlox",
    botanicalName: "Phlox drummondii",
    family: "Polemoniaceae",
    geom: geom(3, 9),
    irr: irr(1.0),
    dtm: 75,
    holding: 21,
    harvests: 8,
    frost: "moderate",
    nursery: 28,
    cell: 128,
    method: "transplant",
    germDays: 8,
    germMin: 60,
    germOpt: 70,
    germMax: 80,
    unitsFt: 8,
    ozUnit: 0.04,
    lbsFt: 0.32,
    cull: 0.12,
    whole: 0.65,
    direct: 1.25,
    n: 1.4,
    p: 0.35,
    k: 1.9,
    interval: 21,
    maxSucc: 2,
    notes: "Cherry Caramel. Cut when ⅓ of the head is open. Fragrant mixer.",
    swatch: "#d6d3d1",
    store: Z2,
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 16,
      supportNetting: net(true, 1, 6, 12, null),
      pinching: pinch(true, 6, 3, 8),
      harvestProtocol: harvest("one-half-open", 3, 6, 8, "citric-acid-hydration", 7),
    },
  },
  dianthus: {
    commonName: "Dianthus",
    botanicalName: "Dianthus barbatus",
    family: "Caryophyllaceae",
    geom: geom(4, 6),
    irr: irr(1.0),
    dtm: 85,
    holding: 16,
    harvests: 4,
    frost: "hardy",
    nursery: 42,
    cell: 128,
    method: "transplant",
    germDays: 8,
    germMin: 60,
    germOpt: 70,
    germMax: 78,
    unitsFt: 8,
    ozUnit: 0.05,
    lbsFt: 0.4,
    cull: 0.1,
    whole: 0.7,
    direct: 1.4,
    n: 1.5,
    p: 0.4,
    k: 2,
    interval: 21,
    maxSucc: 2,
    notes: "Amazon Neon. First-year flowering Sweet William type. Cut ⅓ open. Chlorine shock helps.",
    swatch: "#e11d48",
    store: Z2,
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 20,
      supportNetting: net(true, 1, 6, 12, null),
      pinching: NONE_PINCH,
      harvestProtocol: harvest("one-half-open", 4, 4, 8, "bleach-chlorine-shock", 9),
    },
  },
  rudbeckia: {
    commonName: "Rudbeckia",
    botanicalName: "Rudbeckia hirta",
    family: "Asteraceae",
    geom: geom(3, 12),
    irr: irr(1.0),
    dtm: 85,
    holding: 21,
    harvests: 8,
    frost: "moderate",
    nursery: 35,
    cell: 72,
    method: "transplant",
    germDays: 8,
    germMin: 65,
    germOpt: 75,
    germMax: 85,
    unitsFt: 6,
    ozUnit: 0.06,
    lbsFt: 0.36,
    cull: 0.12,
    whole: 0.55,
    direct: 1.1,
    n: 1.4,
    p: 0.35,
    k: 2,
    interval: 0,
    maxSucc: 1,
    notes: "Indian Summer. Cut as petals unfurl, disk still tight. Heat-capable focal.",
    swatch: "#fbbf24",
    store: { ...Z2, shelf_life_days: 8 },
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 22,
      supportNetting: net(true, 1, 8, 16, null),
      pinching: pinch(true, 8, 3, 10),
      harvestProtocol: harvest("cracked-bud", 3, 8, 6, "plain-cold-water", 8),
    },
  },
  amaranthus: {
    commonName: "Amaranth",
    botanicalName: "Amaranthus cruentus",
    family: "Amaranthaceae",
    geom: geom(2, 12),
    irr: irr(1.1),
    dtm: 80,
    holding: 18,
    harvests: 4,
    frost: "tender",
    nursery: 21,
    cell: 72,
    method: "both",
    germDays: 5,
    germMin: 65,
    germOpt: 75,
    germMax: 90,
    unitsFt: 4,
    ozUnit: 0.1,
    lbsFt: 0.4,
    cull: 0.1,
    whole: 0.8,
    direct: 1.5,
    n: 1.6,
    p: 0.4,
    k: 2.2,
    interval: 21,
    maxSucc: 2,
    notes: "Hot Biscuits / Love-Lies-Bleeding. Cut when tassels are fully colored. No chill.",
    swatch: "#b45309",
    store: { ...Z_TENDER, shelf_life_days: 8 },
    flower: {
      primaryUse: "spike",
      targetStemLengthIn: 28,
      supportNetting: NONE_NET,
      pinching: pinch(true, 10, 3, 8),
      harvestProtocol: harvest("fully-open", 5, 4, 4, "plain-cold-water", 8),
    },
  },
  millet: {
    commonName: "Ornamental millet",
    botanicalName: "Pennisetum glaucum",
    family: "Poaceae",
    geom: geom(2, 12),
    irr: irr(1.1),
    dtm: 70,
    holding: 16,
    harvests: 3,
    frost: "tender",
    nursery: 21,
    cell: 72,
    method: "transplant",
    germDays: 5,
    germMin: 68,
    germOpt: 80,
    germMax: 90,
    unitsFt: 4,
    ozUnit: 0.08,
    lbsFt: 0.32,
    cull: 0.08,
    whole: 0.7,
    direct: 1.35,
    n: 1.5,
    p: 0.35,
    k: 2,
    interval: 14,
    maxSucc: 2,
    notes: "Jester. Cut when the spike is fully emerged, before pollen sheds. Texture spike.",
    swatch: "#854d0e",
    store: { ...Z_TENDER, shelf_life_days: 10 },
    flower: {
      primaryUse: "spike",
      targetStemLengthIn: 26,
      supportNetting: NONE_NET,
      pinching: NONE_PINCH,
      harvestProtocol: harvest("fully-open", 5, 3, 4, "plain-cold-water", 10),
    },
  },
  eucalyptus: {
    commonName: "Eucalyptus",
    botanicalName: "Eucalyptus pulverulenta",
    family: "Myrtaceae",
    geom: geom(2, 18),
    irr: irr(0.9, 1),
    dtm: 150,
    holding: 40,
    harvests: 6,
    frost: "tender",
    nursery: 56,
    cell: 72,
    method: "transplant",
    germDays: 14,
    germMin: 60,
    germOpt: 70,
    germMax: 80,
    unitsFt: 4,
    ozUnit: 0.12,
    lbsFt: 0.48,
    cull: 0.08,
    whole: 1.1,
    direct: 2,
    n: 1.8,
    p: 0.4,
    k: 2.2,
    interval: 0,
    maxSucc: 1,
    notes: "Baby Blue. First-year juvenile foliage. Cut pencil-thick stems. Foliage, not bloom.",
    swatch: "#94a3b8",
    store: { ...Z2, shelf_life_days: 16, harvest_hours_per_100_bed_ft: 2.8 },
    flower: {
      primaryUse: "foliage",
      targetStemLengthIn: 24,
      supportNetting: NONE_NET,
      pinching: pinch(true, 12, 2, 0),
      harvestProtocol: harvest("fully-open", 10, 6, 4, "plain-cold-water", 16),
    },
  },
  dustyMiller: {
    commonName: "Dusty miller",
    botanicalName: "Jacobaea maritima",
    family: "Asteraceae",
    geom: geom(3, 9),
    irr: irr(0.8),
    dtm: 70,
    holding: 28,
    harvests: 6,
    frost: "hardy",
    nursery: 35,
    cell: 128,
    method: "transplant",
    germDays: 10,
    germMin: 60,
    germOpt: 70,
    germMax: 78,
    unitsFt: 6,
    ozUnit: 0.04,
    lbsFt: 0.24,
    cull: 0.08,
    whole: 0.5,
    direct: 1,
    n: 1,
    p: 0.25,
    k: 1.5,
    interval: 0,
    maxSucc: 1,
    notes: "Silver Dust. Foliage cuts. Keep dry-ish. Hardy silver mixer.",
    swatch: "#d4d4d8",
    store: { ...Z2, shelf_life_days: 10 },
    flower: {
      primaryUse: "foliage",
      targetStemLengthIn: 14,
      supportNetting: NONE_NET,
      pinching: pinch(true, 6, 3, 0),
      harvestProtocol: harvest("fully-open", 7, 6, 6, "plain-cold-water", 10),
    },
  },
  sweetPea: {
    commonName: "Sweet pea",
    botanicalName: "Lathyrus odoratus",
    family: "Fabaceae",
    geom: geom(2, 6),
    irr: irr(1.1),
    dtm: 80,
    holding: 21,
    harvests: 10,
    frost: "hardy",
    nursery: 28,
    cell: 72,
    method: "both",
    germDays: 10,
    germMin: 50,
    germOpt: 60,
    germMax: 70,
    unitsFt: 10,
    ozUnit: 0.03,
    lbsFt: 0.3,
    cull: 0.15,
    whole: 0.7,
    direct: 1.5,
    n: 1.2,
    p: 0.3,
    k: 1.8,
    interval: 14,
    maxSucc: 2,
    notes: "Royal Family. Nick seed. Two Hortonova layers as a trellis. Cut daily — pods kill bloom. Cool crop.",
    swatch: "#f9a8d4",
    store: { ...Z2, shelf_life_days: 5 },
    flower: {
      primaryUse: "airy-texture",
      targetStemLengthIn: 12,
      supportNetting: net(true, 2, 6, 12, 30),
      pinching: pinch(true, 6, 2, 8),
      harvestProtocol: harvest("one-half-open", 1, 8, 10, "citric-acid-hydration", 5),
    },
  },
  ranunculus: {
    commonName: "Ranunculus",
    botanicalName: "Ranunculus asiaticus",
    family: "Ranunculaceae",
    geom: geom(4, 6),
    irr: irr(1.0),
    dtm: 95,
    holding: 16,
    harvests: 8,
    frost: "moderate",
    nursery: 84,
    cell: 128,
    method: "transplant",
    germDays: 16,
    germMin: 45,
    germOpt: 55,
    germMax: 65,
    unitsFt: 8,
    ozUnit: 0.05,
    lbsFt: 0.4,
    cull: 0.12,
    whole: 1.15,
    direct: 2.1,
    n: 1.5,
    p: 0.35,
    k: 2,
    interval: 0,
    maxSucc: 1,
    notes: "Bloomingdale class. Pre-sprout claws 10–14 d. Cut at tight bud — they finish in the vase. Cool crop; one Hortonova layer.",
    swatch: "#fb7185",
    store: { ...Z2, shelf_life_days: 8 },
    flower: {
      primaryUse: "focal",
      targetStemLengthIn: 16,
      supportNetting: net(true, 1, 6, 12, null),
      pinching: NONE_PINCH,
      harvestProtocol: harvest("tight-bud", 3, 4, 8, "citric-acid-hydration", 8),
    },
  },
};

type Variant = {
  species: SpeciesKey;
  id: string;
  cultivar: string;
  dtm?: number;
  swatch?: string;
  notes?: string;
  whole?: number;
  direct?: number;
  use?: FlowerUse;
};

const VARIANTS: Variant[] = [
  { species: "zinniaGiant", id: "zinnia-benarys-giant-coral", cultivar: "Benary's Giant Coral", swatch: "#fb7185" },
  { species: "zinniaGiant", id: "zinnia-benarys-giant-lime", cultivar: "Benary's Giant Lime", swatch: "#bef264" },
  { species: "zinniaGiant", id: "zinnia-benarys-giant-wine", cultivar: "Benary's Giant Wine", swatch: "#9f1239" },
  { species: "zinniaBranch", id: "zinnia-oklahoma-salmon", cultivar: "Oklahoma Salmon", swatch: "#fdba74" },
  { species: "zinniaBranch", id: "zinnia-queen-lime-orange", cultivar: "Queen Lime Orange", swatch: "#fbbf24" },
  { species: "zinniaBranch", id: "zinnia-polar-bear", cultivar: "Polar Bear", swatch: "#fafafa" },
  { species: "sunflowerProcut", id: "sunflower-procut-orange", cultivar: "ProCut Orange" },
  { species: "sunflowerProcut", id: "sunflower-procut-white-nite", cultivar: "ProCut White Nite", swatch: "#f4f4f5", notes: "Pollenless cream disk. Same single-stem ProCut rule: never pinch." },
  { species: "sunflowerProcut", id: "sunflower-procut-gold", cultivar: "ProCut Gold", swatch: "#eab308" },
  { species: "sunflowerBranch", id: "sunflower-teddy-bear", cultivar: "Teddy Bear", swatch: "#ca8a04" },
  { species: "snapGroup1", id: "snapdragon-potomac-red", cultivar: "Potomac Red" },
  { species: "snapGroup1", id: "snapdragon-potomac-white", cultivar: "Potomac White", swatch: "#fafafa" },
  { species: "snapGroup1", id: "snapdragon-maryland-appleblossom", cultivar: "Maryland Appleblossom", swatch: "#fecdd3", notes: "Group 1/2 shoulder. Do not pinch. Two-layer Hortonova." },
  { species: "snapGroup3", id: "snapdragon-rocket-mix", cultivar: "Rocket Mix" },
  { species: "lisianthus", id: "lisianthus-abc-2-rose", cultivar: "ABC 2 Rose", swatch: "#f9a8d4" },
  { species: "lisianthus", id: "lisianthus-mariachi-blue", cultivar: "Mariachi Blue", swatch: "#818cf8" },
  { species: "lisianthus", id: "lisianthus-corelli-white", cultivar: "Corelli White", swatch: "#fafafa" },
  { species: "dahlia", id: "dahlia-cafe-au-lait", cultivar: "Café au Lait", swatch: "#fecaca" },
  { species: "dahlia", id: "dahlia-karma-corona", cultivar: "Karma Corona", swatch: "#fb923c" },
  { species: "dahlia", id: "dahlia-arabian-night", cultivar: "Arabian Night", swatch: "#7f1d1d" },
  { species: "cosmos", id: "cosmos-double-click-cranberry", cultivar: "Double Click Cranberry", swatch: "#9f1239" },
  { species: "cosmos", id: "cosmos-purity", cultivar: "Purity", swatch: "#fafafa" },
  { species: "cosmos", id: "cosmos-seashells", cultivar: "Seashells", swatch: "#fda4af" },
  { species: "scabiosa", id: "scabiosa-black-knight", cultivar: "Black Knight" },
  { species: "scabiosa", id: "scabiosa-fata-morgana", cultivar: "Fata Morgana", swatch: "#fde68a" },
  { species: "stock", id: "stock-katz-white", cultivar: "Katz White", swatch: "#fafafa" },
  { species: "stock", id: "stock-katz-bright-rose", cultivar: "Katz Bright Rose", swatch: "#e11d48" },
  { species: "celosia", id: "celosia-chief-persimmon", cultivar: "Chief Persimmon" },
  { species: "celosia", id: "celosia-celway-white", cultivar: "Celway White", swatch: "#f4f4f5", use: "spike" },
  { species: "celosia", id: "celosia-flamingo-feather", cultivar: "Flamingo Feather", swatch: "#f9a8d4", use: "spike" },
  { species: "statice", id: "statice-qis-white", cultivar: "QIS White" },
  { species: "gomphrena", id: "gomphrena-qis-carmine", cultivar: "QIS Carmine" },
  { species: "ammi", id: "ammi-green-mist", cultivar: "Green Mist" },
  { species: "bupleurum", id: "bupleurum-griffithii", cultivar: "Griffithii" },
  { species: "feverfew", id: "feverfew-vegmo-snowball", cultivar: "Vegmo Snowball" },
  { species: "yarrow", id: "yarrow-summer-pastels", cultivar: "Summer Pastels" },
  { species: "nigella", id: "nigella-miss-jekyll", cultivar: "Miss Jekyll" },
  { species: "craspedia", id: "craspedia-golf-beauty", cultivar: "Golf Beauty" },
  { species: "strawflower", id: "strawflower-swiss-giant-mix", cultivar: "Swiss Giant Mix" },
  { species: "larkspur", id: "larkspur-giant-imperial", cultivar: "Giant Imperial Mix" },
  { species: "bells", id: "bells-of-ireland", cultivar: "Bells of Ireland" },
  { species: "phlox", id: "phlox-cherry-caramel", cultivar: "Cherry Caramel" },
  { species: "dianthus", id: "dianthus-amazon-neon-cherry", cultivar: "Amazon Neon Cherry" },
  { species: "rudbeckia", id: "rudbeckia-indian-summer", cultivar: "Indian Summer" },
  { species: "amaranthus", id: "amaranthus-hot-biscuits", cultivar: "Hot Biscuits" },
  { species: "millet", id: "millet-jester", cultivar: "Jester" },
  { species: "eucalyptus", id: "eucalyptus-baby-blue", cultivar: "Baby Blue" },
  { species: "dustyMiller", id: "dusty-miller-silver-dust", cultivar: "Silver Dust" },
  { species: "sweetPea", id: "sweet-pea-royal-family", cultivar: "Royal Family Mix" },
  { species: "ranunculus", id: "ranunculus-bloomingdale-mix", cultivar: "Bloomingdale Mix" },
];

function expand(species: SpeciesKey, v: Variant): Crop {
  const t = S[species];
  const flower: CutFlowerSpecifics = {
    ...t.flower,
    primaryUse: v.use ?? t.flower.primaryUse,
  };
  const dtm = (v.dtm ?? t.dtm) + (flower.pinching.required ? flower.pinching.dtmPenaltyDays : 0);
  return {
    id: v.id,
    commonName: t.commonName,
    cultivar: v.cultivar,
    botanicalName: t.botanicalName,
    family: t.family,
    category: "cut-flowers",
    flowerSpecifics: flower,
    propagation: {
      method: t.method,
      recommendedCellSize: t.cell,
      nurseryLeadDays: t.nursery,
      germinationDays: t.germDays,
      minGermTempF: t.germMin,
      optimumGermTempF: t.germOpt,
      maxGermTempF: t.germMax,
    },
    fieldGeometry: t.geom,
    timeline: {
      dtmFromField: dtm,
      fieldHoldingDays: t.holding,
      isMulticut: t.harvests > 1,
      regrowthDays: t.harvests > 1 ? Math.max(3, flower.harvestProtocol.cutFrequencyDays) : null,
      maxHarvests: t.harvests,
      fallPhotoperiodMultiplier: 1,
      frostHardiness: t.frost,
    },
    yieldAndRevenue: {
      salesUnit: "stem",
      unitsPerBedFoot: t.unitsFt,
      avgWeightPerUnitLbs: t.ozUnit,
      targetYieldLbsPerBedFoot: t.lbsFt,
      standardCullRate: t.cull,
      targetWholesalePriceUsd: v.whole ?? t.whole,
      targetDirectPriceUsd: v.direct ?? t.direct,
    },
    irrigationProfile: t.irr,
    soilExtractionProfile: {
      fertilityDemand: t.n >= 1.8 ? "heavy" : t.n <= 1.1 ? "light" : "moderate",
      nRemovalLbsPer100BedFt: t.n,
      pRemovalLbsPer100BedFt: t.p,
      kRemovalLbsPer100BedFt: t.k,
    },
    successionIntervalDays: t.interval,
    maxSuccessions: t.maxSucc,
    companions: ["basil", "dill", "alyssum"],
    avoid: ["fennel"],
    notes: v.notes ?? t.notes,
    swatch: v.swatch ?? t.swatch,
  };
}

export const FLOWER_DATABASE: Crop[] = VARIANTS.map((row) => expand(row.species, row));

function isMain(): boolean {
  const self = fileURLToPath(import.meta.url);
  const invoked = process.argv[1] ? join(process.argv[1]) : "";
  return self === invoked || invoked.endsWith("seed-flowers.ts");
}

export function seedFlowers(): { written: number; skipped: number; specs: number; flowers: number } {
  if (!existsSync(cropDir)) mkdirSync(cropDir, { recursive: true });
  const ids = new Set<string>();
  let written = 0;
  let skipped = 0;
  const newSpecs: CropPostHarvestSpec[] = [];

  for (const row of VARIANTS) {
    if (ids.has(row.id)) throw new Error(`Duplicate flower id: ${row.id}`);
    ids.add(row.id);
    const crop = expand(row.species, row);
    const file = join(cropDir, `${crop.id}.json`);
    if (existsSync(file)) {
      const existing = JSON.parse(readFileSync(file, "utf8")) as { category?: string };
      if (existing.category !== "cut-flowers") {
        skipped += 1;
        continue;
      }
    }
    writeFileSync(file, `${JSON.stringify(crop, null, 2)}\n`, "utf8");
    written += 1;
    newSpecs.push({ crop_id: crop.id, ...S[row.species].store });
  }

  const existing: CropPostHarvestSpec[] = existsSync(storagePath)
    ? (JSON.parse(readFileSync(storagePath, "utf8")) as CropPostHarvestSpec[])
    : [];
  const specById = new Map(existing.map((s) => [s.crop_id, s]));
  for (const spec of newSpecs) {
    if (!specById.has(spec.crop_id)) specById.set(spec.crop_id, spec);
  }
  const specs = [...specById.values()].sort((a, b) => a.crop_id.localeCompare(b.crop_id));
  writeFileSync(storagePath, `${JSON.stringify(specs, null, 2)}\n`, "utf8");

  return { written, skipped, specs: specs.length, flowers: VARIANTS.length };
}

if (isMain()) {
  const result = seedFlowers();
  console.log(
    `Seeded ${result.written} cut-flower files (${result.skipped} vegetable collisions skipped). Flowers in seed: ${result.flowers}. Storage specs: ${result.specs}.`,
  );
}
