/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClipboardRouteImport } from './routes/clipboard'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as CropSlugRouteImport } from './routes/crop/$slug'
import { Route as CropsIndexRouteImport } from './routes/crops/index'
import { Route as EconomicsIndexRouteImport } from './routes/economics/index'
import { Route as EconomicsSlugRouteImport } from './routes/economics/$slug'
import { Route as IrrigationIndexRouteImport } from './routes/irrigation/index'
import { Route as IrrigationSlugRouteImport } from './routes/irrigation/$slug'
import { Route as NurseryIndexRouteImport } from './routes/nursery/index'
import { Route as NurserySlugRouteImport } from './routes/nursery/$slug'
import { Route as PastureIndexRouteImport } from './routes/pasture/index'
import { Route as PastureSlugRouteImport } from './routes/pasture/$slug'
import { Route as SoilIndexRouteImport } from './routes/soil/index'
import { Route as SoilSlugRouteImport } from './routes/soil/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipboardRoute = ClipboardRouteImport.update({
  id: '/clipboard',
  path: '/clipboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const CropSlugRoute = CropSlugRouteImport.update({
  id: '/crop/$slug',
  path: '/crop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsIndexRoute = CropsIndexRouteImport.update({
  id: '/crops/',
  path: '/crops/',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsIndexRoute = EconomicsIndexRouteImport.update({
  id: '/economics/',
  path: '/economics/',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsSlugRoute = EconomicsSlugRouteImport.update({
  id: '/economics/$slug',
  path: '/economics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IrrigationIndexRoute = IrrigationIndexRouteImport.update({
  id: '/irrigation/',
  path: '/irrigation/',
  getParentRoute: () => rootRouteImport,
} as any)
const IrrigationSlugRoute = IrrigationSlugRouteImport.update({
  id: '/irrigation/$slug',
  path: '/irrigation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseryIndexRoute = NurseryIndexRouteImport.update({
  id: '/nursery/',
  path: '/nursery/',
  getParentRoute: () => rootRouteImport,
} as any)
const NurserySlugRoute = NurserySlugRouteImport.update({
  id: '/nursery/$slug',
  path: '/nursery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PastureIndexRoute = PastureIndexRouteImport.update({
  id: '/pasture/',
  path: '/pasture/',
  getParentRoute: () => rootRouteImport,
} as any)
const PastureSlugRoute = PastureSlugRouteImport.update({
  id: '/pasture/$slug',
  path: '/pasture/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilIndexRoute = SoilIndexRouteImport.update({
  id: '/soil/',
  path: '/soil/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilSlugRoute = SoilSlugRouteImport.update({
  id: '/soil/$slug',
  path: '/soil/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clipboard': typeof ClipboardRoute
  '/engine': typeof EngineRoute
  '/crop/$slug': typeof CropSlugRoute
  '/economics/$slug': typeof EconomicsSlugRoute
  '/irrigation/$slug': typeof IrrigationSlugRoute
  '/nursery/$slug': typeof NurserySlugRoute
  '/pasture/$slug': typeof PastureSlugRoute
  '/soil/$slug': typeof SoilSlugRoute
  '/crops/': typeof CropsIndexRoute
  '/economics/': typeof EconomicsIndexRoute
  '/irrigation/': typeof IrrigationIndexRoute
  '/nursery/': typeof NurseryIndexRoute
  '/pasture/': typeof PastureIndexRoute
  '/soil/': typeof SoilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clipboard': typeof ClipboardRoute
  '/engine': typeof EngineRoute
  '/crop/$slug': typeof CropSlugRoute
  '/economics/$slug': typeof EconomicsSlugRoute
  '/irrigation/$slug': typeof IrrigationSlugRoute
  '/nursery/$slug': typeof NurserySlugRoute
  '/pasture/$slug': typeof PastureSlugRoute
  '/soil/$slug': typeof SoilSlugRoute
  '/crops': typeof CropsIndexRoute
  '/economics': typeof EconomicsIndexRoute
  '/irrigation': typeof IrrigationIndexRoute
  '/nursery': typeof NurseryIndexRoute
  '/pasture': typeof PastureIndexRoute
  '/soil': typeof SoilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clipboard': typeof ClipboardRoute
  '/engine': typeof EngineRoute
  '/crop/$slug': typeof CropSlugRoute
  '/economics/$slug': typeof EconomicsSlugRoute
  '/irrigation/$slug': typeof IrrigationSlugRoute
  '/nursery/$slug': typeof NurserySlugRoute
  '/pasture/$slug': typeof PastureSlugRoute
  '/soil/$slug': typeof SoilSlugRoute
  '/crops/': typeof CropsIndexRoute
  '/economics/': typeof EconomicsIndexRoute
  '/irrigation/': typeof IrrigationIndexRoute
  '/nursery/': typeof NurseryIndexRoute
  '/pasture/': typeof PastureIndexRoute
  '/soil/': typeof SoilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clipboard'
    | '/engine'
    | '/crop/$slug'
    | '/economics/$slug'
    | '/irrigation/$slug'
    | '/nursery/$slug'
    | '/pasture/$slug'
    | '/soil/$slug'
    | '/crops/'
    | '/economics/'
    | '/irrigation/'
    | '/nursery/'
    | '/pasture/'
    | '/soil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clipboard'
    | '/engine'
    | '/crop/$slug'
    | '/economics/$slug'
    | '/irrigation/$slug'
    | '/nursery/$slug'
    | '/pasture/$slug'
    | '/soil/$slug'
    | '/crops'
    | '/economics'
    | '/irrigation'
    | '/nursery'
    | '/pasture'
    | '/soil'
  id:
    | '__root__'
    | '/'
    | '/clipboard'
    | '/engine'
    | '/crop/$slug'
    | '/economics/$slug'
    | '/irrigation/$slug'
    | '/nursery/$slug'
    | '/pasture/$slug'
    | '/soil/$slug'
    | '/crops/'
    | '/economics/'
    | '/irrigation/'
    | '/nursery/'
    | '/pasture/'
    | '/soil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClipboardRoute: typeof ClipboardRoute
  EngineRoute: typeof EngineRoute
  CropSlugRoute: typeof CropSlugRoute
  EconomicsSlugRoute: typeof EconomicsSlugRoute
  IrrigationSlugRoute: typeof IrrigationSlugRoute
  NurserySlugRoute: typeof NurserySlugRoute
  PastureSlugRoute: typeof PastureSlugRoute
  SoilSlugRoute: typeof SoilSlugRoute
  CropsIndexRoute: typeof CropsIndexRoute
  EconomicsIndexRoute: typeof EconomicsIndexRoute
  IrrigationIndexRoute: typeof IrrigationIndexRoute
  NurseryIndexRoute: typeof NurseryIndexRoute
  PastureIndexRoute: typeof PastureIndexRoute
  SoilIndexRoute: typeof SoilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clipboard': {
      id: '/clipboard'
      path: '/clipboard'
      fullPath: '/clipboard'
      preLoaderRoute: typeof ClipboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop/$slug': {
      id: '/crop/$slug'
      path: '/crop/$slug'
      fullPath: '/crop/$slug'
      preLoaderRoute: typeof CropSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/': {
      id: '/crops/'
      path: '/crops'
      fullPath: '/crops/'
      preLoaderRoute: typeof CropsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics/': {
      id: '/economics/'
      path: '/economics'
      fullPath: '/economics/'
      preLoaderRoute: typeof EconomicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics/$slug': {
      id: '/economics/$slug'
      path: '/economics/$slug'
      fullPath: '/economics/$slug'
      preLoaderRoute: typeof EconomicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irrigation/': {
      id: '/irrigation/'
      path: '/irrigation'
      fullPath: '/irrigation/'
      preLoaderRoute: typeof IrrigationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irrigation/$slug': {
      id: '/irrigation/$slug'
      path: '/irrigation/$slug'
      fullPath: '/irrigation/$slug'
      preLoaderRoute: typeof IrrigationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nursery/': {
      id: '/nursery/'
      path: '/nursery'
      fullPath: '/nursery/'
      preLoaderRoute: typeof NurseryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nursery/$slug': {
      id: '/nursery/$slug'
      path: '/nursery/$slug'
      fullPath: '/nursery/$slug'
      preLoaderRoute: typeof NurserySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasture/': {
      id: '/pasture/'
      path: '/pasture'
      fullPath: '/pasture/'
      preLoaderRoute: typeof PastureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasture/$slug': {
      id: '/pasture/$slug'
      path: '/pasture/$slug'
      fullPath: '/pasture/$slug'
      preLoaderRoute: typeof PastureSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil/': {
      id: '/soil/'
      path: '/soil'
      fullPath: '/soil/'
      preLoaderRoute: typeof SoilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil/$slug': {
      id: '/soil/$slug'
      path: '/soil/$slug'
      fullPath: '/soil/$slug'
      preLoaderRoute: typeof SoilSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClipboardRoute: ClipboardRoute,
  EngineRoute: EngineRoute,
  CropSlugRoute: CropSlugRoute,
  EconomicsSlugRoute: EconomicsSlugRoute,
  IrrigationSlugRoute: IrrigationSlugRoute,
  NurserySlugRoute: NurserySlugRoute,
  PastureSlugRoute: PastureSlugRoute,
  SoilSlugRoute: SoilSlugRoute,
  CropsIndexRoute: CropsIndexRoute,
  EconomicsIndexRoute: EconomicsIndexRoute,
  IrrigationIndexRoute: IrrigationIndexRoute,
  NurseryIndexRoute: NurseryIndexRoute,
  PastureIndexRoute: PastureIndexRoute,
  SoilIndexRoute: SoilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
