/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClipRouteImport } from './routes/clip'
import { Route as ClipboardRouteImport } from './routes/clipboard'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as CropSlugRouteImport } from './routes/crop/$slug'
import { Route as CropsIndexRouteImport } from './routes/crops/index'
import { Route as EconomicsIndexRouteImport } from './routes/economics/index'
import { Route as EconomicsSlugRouteImport } from './routes/economics/$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as Guides30InchBedPrepRouteImport } from './routes/guides/30-inch-bed-prep'
import { Route as GuidesCoverCropsSmallAcreageRouteImport } from './routes/guides/cover-crops-small-acreage'
import { Route as GuidesDaysToMaturityFallHarvestRouteImport } from './routes/guides/days-to-maturity-fall-harvest'
import { Route as GuidesDirectSowVsTransplantRouteImport } from './routes/guides/direct-sow-vs-transplant'
import { Route as GuidesDripIrrigationQuarterAcreRouteImport } from './routes/guides/drip-irrigation-quarter-acre'
import { Route as GuidesDripIrrigationRunTimeRouteImport } from './routes/guides/drip-irrigation-run-time'
import { Route as GuidesMicrogreensSeedDensityRouteImport } from './routes/guides/microgreens-seed-density'
import { Route as GuidesPastureRestDaysRouteImport } from './routes/guides/pasture-rest-days'
import { Route as GuidesSoilBlockingTransplantsRouteImport } from './routes/guides/soil-blocking-transplants'
import { Route as GuidesSuccessionPlantingSaladGreensRouteImport } from './routes/guides/succession-planting-salad-greens'
import { Route as GuidesSuccessionPlantingScheduleRouteImport } from './routes/guides/succession-planting-schedule'
import { Route as GuidesWalkInCoolerManagementRouteImport } from './routes/guides/walk-in-cooler-management'
import { Route as IrrigationIndexRouteImport } from './routes/irrigation/index'
import { Route as IrrigationSlugRouteImport } from './routes/irrigation/$slug'
import { Route as NurseryIndexRouteImport } from './routes/nursery/index'
import { Route as NurserySlugRouteImport } from './routes/nursery/$slug'
import { Route as PastureIndexRouteImport } from './routes/pasture/index'
import { Route as PastureSlugRouteImport } from './routes/pasture/$slug'
import { Route as PrintClipboardRouteImport } from './routes/print.clipboard'
import { Route as SoilIndexRouteImport } from './routes/soil/index'
import { Route as SoilSlugRouteImport } from './routes/soil/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipRoute = ClipRouteImport.update({
  id: '/clip',
  path: '/clip',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipboardRoute = ClipboardRouteImport.update({
  id: '/clipboard',
  path: '/clipboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const CropSlugRoute = CropSlugRouteImport.update({
  id: '/crop/$slug',
  path: '/crop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsIndexRoute = CropsIndexRouteImport.update({
  id: '/crops/',
  path: '/crops/',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsIndexRoute = EconomicsIndexRouteImport.update({
  id: '/economics/',
  path: '/economics/',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomicsSlugRoute = EconomicsSlugRouteImport.update({
  id: '/economics/$slug',
  path: '/economics/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const Guides30InchBedPrepRoute = Guides30InchBedPrepRouteImport.update({
  id: '/guides/30-inch-bed-prep',
  path: '/guides/30-inch-bed-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesCoverCropsSmallAcreageRoute =
  GuidesCoverCropsSmallAcreageRouteImport.update({
    id: '/guides/cover-crops-small-acreage',
    path: '/guides/cover-crops-small-acreage',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesDaysToMaturityFallHarvestRoute =
  GuidesDaysToMaturityFallHarvestRouteImport.update({
    id: '/guides/days-to-maturity-fall-harvest',
    path: '/guides/days-to-maturity-fall-harvest',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesDirectSowVsTransplantRoute =
  GuidesDirectSowVsTransplantRouteImport.update({
    id: '/guides/direct-sow-vs-transplant',
    path: '/guides/direct-sow-vs-transplant',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesDripIrrigationQuarterAcreRoute =
  GuidesDripIrrigationQuarterAcreRouteImport.update({
    id: '/guides/drip-irrigation-quarter-acre',
    path: '/guides/drip-irrigation-quarter-acre',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesDripIrrigationRunTimeRoute =
  GuidesDripIrrigationRunTimeRouteImport.update({
    id: '/guides/drip-irrigation-run-time',
    path: '/guides/drip-irrigation-run-time',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesMicrogreensSeedDensityRoute =
  GuidesMicrogreensSeedDensityRouteImport.update({
    id: '/guides/microgreens-seed-density',
    path: '/guides/microgreens-seed-density',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesPastureRestDaysRoute = GuidesPastureRestDaysRouteImport.update({
  id: '/guides/pasture-rest-days',
  path: '/guides/pasture-rest-days',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSoilBlockingTransplantsRoute =
  GuidesSoilBlockingTransplantsRouteImport.update({
    id: '/guides/soil-blocking-transplants',
    path: '/guides/soil-blocking-transplants',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesSuccessionPlantingSaladGreensRoute =
  GuidesSuccessionPlantingSaladGreensRouteImport.update({
    id: '/guides/succession-planting-salad-greens',
    path: '/guides/succession-planting-salad-greens',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesSuccessionPlantingScheduleRoute =
  GuidesSuccessionPlantingScheduleRouteImport.update({
    id: '/guides/succession-planting-schedule',
    path: '/guides/succession-planting-schedule',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesWalkInCoolerManagementRoute =
  GuidesWalkInCoolerManagementRouteImport.update({
    id: '/guides/walk-in-cooler-management',
    path: '/guides/walk-in-cooler-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const IrrigationIndexRoute = IrrigationIndexRouteImport.update({
  id: '/irrigation/',
  path: '/irrigation/',
  getParentRoute: () => rootRouteImport,
} as any)
const IrrigationSlugRoute = IrrigationSlugRouteImport.update({
  id: '/irrigation/$slug',
  path: '/irrigation/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseryIndexRoute = NurseryIndexRouteImport.update({
  id: '/nursery/',
  path: '/nursery/',
  getParentRoute: () => rootRouteImport,
} as any)
const NurserySlugRoute = NurserySlugRouteImport.update({
  id: '/nursery/$slug',
  path: '/nursery/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PastureIndexRoute = PastureIndexRouteImport.update({
  id: '/pasture/',
  path: '/pasture/',
  getParentRoute: () => rootRouteImport,
} as any)
const PastureSlugRoute = PastureSlugRouteImport.update({
  id: '/pasture/$slug',
  path: '/pasture/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintClipboardRoute = PrintClipboardRouteImport.update({
  id: '/print/clipboard',
  path: '/print/clipboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilIndexRoute = SoilIndexRouteImport.update({
  id: '/soil/',
  path: '/soil/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoilSlugRoute = SoilSlugRouteImport.update({
  id: '/soil/$slug',
  path: '/soil/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clip': typeof ClipRoute
  '/clipboard': typeof ClipboardRoute
  '/engine': typeof EngineRoute
  '/crop/$slug': typeof CropSlugRoute
  '/economics/$slug': typeof EconomicsSlugRoute
  '/guides/30-inch-bed-prep': typeof Guides30InchBedPrepRoute
  '/guides/cover-crops-small-acreage': typeof GuidesCoverCropsSmallAcreageRoute
  '/guides/days-to-maturity-fall-harvest': typeof GuidesDaysToMaturityFallHarvestRoute
  '/guides/direct-sow-vs-transplant': typeof GuidesDirectSowVsTransplantRoute
  '/guides/drip-irrigation-quarter-acre': typeof GuidesDripIrrigationQuarterAcreRoute
  '/guides/drip-irrigation-run-time': typeof GuidesDripIrrigationRunTimeRoute
  '/guides/microgreens-seed-density': typeof GuidesMicrogreensSeedDensityRoute
  '/guides/pasture-rest-days': typeof GuidesPastureRestDaysRoute
  '/guides/soil-blocking-transplants': typeof GuidesSoilBlockingTransplantsRoute
  '/guides/succession-planting-salad-greens': typeof GuidesSuccessionPlantingSaladGreensRoute
  '/guides/succession-planting-schedule': typeof GuidesSuccessionPlantingScheduleRoute
  '/guides/walk-in-cooler-management': typeof GuidesWalkInCoolerManagementRoute
  '/irrigation/$slug': typeof IrrigationSlugRoute
  '/nursery/$slug': typeof NurserySlugRoute
  '/pasture/$slug': typeof PastureSlugRoute
  '/print/clipboard': typeof PrintClipboardRoute
  '/soil/$slug': typeof SoilSlugRoute
  '/crops/': typeof CropsIndexRoute
  '/economics/': typeof EconomicsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/irrigation/': typeof IrrigationIndexRoute
  '/nursery/': typeof NurseryIndexRoute
  '/pasture/': typeof PastureIndexRoute
  '/soil/': typeof SoilIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clip': typeof ClipRoute
  '/clipboard': typeof ClipboardRoute
  '/engine': typeof EngineRoute
  '/crop/$slug': typeof CropSlugRoute
  '/economics/$slug': typeof EconomicsSlugRoute
  '/guides/30-inch-bed-prep': typeof Guides30InchBedPrepRoute
  '/guides/cover-crops-small-acreage': typeof GuidesCoverCropsSmallAcreageRoute
  '/guides/days-to-maturity-fall-harvest': typeof GuidesDaysToMaturityFallHarvestRoute
  '/guides/direct-sow-vs-transplant': typeof GuidesDirectSowVsTransplantRoute
  '/guides/drip-irrigation-quarter-acre': typeof GuidesDripIrrigationQuarterAcreRoute
  '/guides/drip-irrigation-run-time': typeof GuidesDripIrrigationRunTimeRoute
  '/guides/microgreens-seed-density': typeof GuidesMicrogreensSeedDensityRoute
  '/guides/pasture-rest-days': typeof GuidesPastureRestDaysRoute
  '/guides/soil-blocking-transplants': typeof GuidesSoilBlockingTransplantsRoute
  '/guides/succession-planting-salad-greens': typeof GuidesSuccessionPlantingSaladGreensRoute
  '/guides/succession-planting-schedule': typeof GuidesSuccessionPlantingScheduleRoute
  '/guides/walk-in-cooler-management': typeof GuidesWalkInCoolerManagementRoute
  '/irrigation/$slug': typeof IrrigationSlugRoute
  '/nursery/$slug': typeof NurserySlugRoute
  '/pasture/$slug': typeof PastureSlugRoute
  '/print/clipboard': typeof PrintClipboardRoute
  '/soil/$slug': typeof SoilSlugRoute
  '/crops': typeof CropsIndexRoute
  '/economics': typeof EconomicsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/irrigation': typeof IrrigationIndexRoute
  '/nursery': typeof NurseryIndexRoute
  '/pasture': typeof PastureIndexRoute
  '/soil': typeof SoilIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clip': typeof ClipRoute
  '/clipboard': typeof ClipboardRoute
  '/engine': typeof EngineRoute
  '/crop/$slug': typeof CropSlugRoute
  '/economics/$slug': typeof EconomicsSlugRoute
  '/guides/30-inch-bed-prep': typeof Guides30InchBedPrepRoute
  '/guides/cover-crops-small-acreage': typeof GuidesCoverCropsSmallAcreageRoute
  '/guides/days-to-maturity-fall-harvest': typeof GuidesDaysToMaturityFallHarvestRoute
  '/guides/direct-sow-vs-transplant': typeof GuidesDirectSowVsTransplantRoute
  '/guides/drip-irrigation-quarter-acre': typeof GuidesDripIrrigationQuarterAcreRoute
  '/guides/drip-irrigation-run-time': typeof GuidesDripIrrigationRunTimeRoute
  '/guides/microgreens-seed-density': typeof GuidesMicrogreensSeedDensityRoute
  '/guides/pasture-rest-days': typeof GuidesPastureRestDaysRoute
  '/guides/soil-blocking-transplants': typeof GuidesSoilBlockingTransplantsRoute
  '/guides/succession-planting-salad-greens': typeof GuidesSuccessionPlantingSaladGreensRoute
  '/guides/succession-planting-schedule': typeof GuidesSuccessionPlantingScheduleRoute
  '/guides/walk-in-cooler-management': typeof GuidesWalkInCoolerManagementRoute
  '/irrigation/$slug': typeof IrrigationSlugRoute
  '/nursery/$slug': typeof NurserySlugRoute
  '/pasture/$slug': typeof PastureSlugRoute
  '/print/clipboard': typeof PrintClipboardRoute
  '/soil/$slug': typeof SoilSlugRoute
  '/crops/': typeof CropsIndexRoute
  '/economics/': typeof EconomicsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/irrigation/': typeof IrrigationIndexRoute
  '/nursery/': typeof NurseryIndexRoute
  '/pasture/': typeof PastureIndexRoute
  '/soil/': typeof SoilIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clip'
    | '/clipboard'
    | '/engine'
    | '/crop/$slug'
    | '/economics/$slug'
    | '/guides/30-inch-bed-prep'
    | '/guides/cover-crops-small-acreage'
    | '/guides/days-to-maturity-fall-harvest'
    | '/guides/direct-sow-vs-transplant'
    | '/guides/drip-irrigation-quarter-acre'
    | '/guides/drip-irrigation-run-time'
    | '/guides/microgreens-seed-density'
    | '/guides/pasture-rest-days'
    | '/guides/soil-blocking-transplants'
    | '/guides/succession-planting-salad-greens'
    | '/guides/succession-planting-schedule'
    | '/guides/walk-in-cooler-management'
    | '/irrigation/$slug'
    | '/nursery/$slug'
    | '/pasture/$slug'
    | '/print/clipboard'
    | '/soil/$slug'
    | '/crops/'
    | '/economics/'
    | '/guides/'
    | '/irrigation/'
    | '/nursery/'
    | '/pasture/'
    | '/soil/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clip'
    | '/clipboard'
    | '/engine'
    | '/crop/$slug'
    | '/economics/$slug'
    | '/guides/30-inch-bed-prep'
    | '/guides/cover-crops-small-acreage'
    | '/guides/days-to-maturity-fall-harvest'
    | '/guides/direct-sow-vs-transplant'
    | '/guides/drip-irrigation-quarter-acre'
    | '/guides/drip-irrigation-run-time'
    | '/guides/microgreens-seed-density'
    | '/guides/pasture-rest-days'
    | '/guides/soil-blocking-transplants'
    | '/guides/succession-planting-salad-greens'
    | '/guides/succession-planting-schedule'
    | '/guides/walk-in-cooler-management'
    | '/irrigation/$slug'
    | '/nursery/$slug'
    | '/pasture/$slug'
    | '/print/clipboard'
    | '/soil/$slug'
    | '/crops'
    | '/economics'
    | '/guides'
    | '/irrigation'
    | '/nursery'
    | '/pasture'
    | '/soil'
  id:
    | '__root__'
    | '/'
    | '/clip'
    | '/clipboard'
    | '/engine'
    | '/crop/$slug'
    | '/economics/$slug'
    | '/guides/30-inch-bed-prep'
    | '/guides/cover-crops-small-acreage'
    | '/guides/days-to-maturity-fall-harvest'
    | '/guides/direct-sow-vs-transplant'
    | '/guides/drip-irrigation-quarter-acre'
    | '/guides/drip-irrigation-run-time'
    | '/guides/microgreens-seed-density'
    | '/guides/pasture-rest-days'
    | '/guides/soil-blocking-transplants'
    | '/guides/succession-planting-salad-greens'
    | '/guides/succession-planting-schedule'
    | '/guides/walk-in-cooler-management'
    | '/irrigation/$slug'
    | '/nursery/$slug'
    | '/pasture/$slug'
    | '/print/clipboard'
    | '/soil/$slug'
    | '/crops/'
    | '/economics/'
    | '/guides/'
    | '/irrigation/'
    | '/nursery/'
    | '/pasture/'
    | '/soil/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClipRoute: typeof ClipRoute
  ClipboardRoute: typeof ClipboardRoute
  EngineRoute: typeof EngineRoute
  CropSlugRoute: typeof CropSlugRoute
  EconomicsSlugRoute: typeof EconomicsSlugRoute
  Guides30InchBedPrepRoute: typeof Guides30InchBedPrepRoute
  GuidesCoverCropsSmallAcreageRoute: typeof GuidesCoverCropsSmallAcreageRoute
  GuidesDaysToMaturityFallHarvestRoute: typeof GuidesDaysToMaturityFallHarvestRoute
  GuidesDirectSowVsTransplantRoute: typeof GuidesDirectSowVsTransplantRoute
  GuidesDripIrrigationQuarterAcreRoute: typeof GuidesDripIrrigationQuarterAcreRoute
  GuidesDripIrrigationRunTimeRoute: typeof GuidesDripIrrigationRunTimeRoute
  GuidesMicrogreensSeedDensityRoute: typeof GuidesMicrogreensSeedDensityRoute
  GuidesPastureRestDaysRoute: typeof GuidesPastureRestDaysRoute
  GuidesSoilBlockingTransplantsRoute: typeof GuidesSoilBlockingTransplantsRoute
  GuidesSuccessionPlantingSaladGreensRoute: typeof GuidesSuccessionPlantingSaladGreensRoute
  GuidesSuccessionPlantingScheduleRoute: typeof GuidesSuccessionPlantingScheduleRoute
  GuidesWalkInCoolerManagementRoute: typeof GuidesWalkInCoolerManagementRoute
  IrrigationSlugRoute: typeof IrrigationSlugRoute
  NurserySlugRoute: typeof NurserySlugRoute
  PastureSlugRoute: typeof PastureSlugRoute
  PrintClipboardRoute: typeof PrintClipboardRoute
  SoilSlugRoute: typeof SoilSlugRoute
  CropsIndexRoute: typeof CropsIndexRoute
  EconomicsIndexRoute: typeof EconomicsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  IrrigationIndexRoute: typeof IrrigationIndexRoute
  NurseryIndexRoute: typeof NurseryIndexRoute
  PastureIndexRoute: typeof PastureIndexRoute
  SoilIndexRoute: typeof SoilIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clip': {
      id: '/clip'
      path: '/clip'
      fullPath: '/clip'
      preLoaderRoute: typeof ClipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clipboard': {
      id: '/clipboard'
      path: '/clipboard'
      fullPath: '/clipboard'
      preLoaderRoute: typeof ClipboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop/$slug': {
      id: '/crop/$slug'
      path: '/crop/$slug'
      fullPath: '/crop/$slug'
      preLoaderRoute: typeof CropSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/': {
      id: '/crops/'
      path: '/crops'
      fullPath: '/crops/'
      preLoaderRoute: typeof CropsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics/': {
      id: '/economics/'
      path: '/economics'
      fullPath: '/economics/'
      preLoaderRoute: typeof EconomicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economics/$slug': {
      id: '/economics/$slug'
      path: '/economics/$slug'
      fullPath: '/economics/$slug'
      preLoaderRoute: typeof EconomicsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/30-inch-bed-prep': {
      id: '/guides/30-inch-bed-prep'
      path: '/guides/30-inch-bed-prep'
      fullPath: '/guides/30-inch-bed-prep'
      preLoaderRoute: typeof Guides30InchBedPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/cover-crops-small-acreage': {
      id: '/guides/cover-crops-small-acreage'
      path: '/guides/cover-crops-small-acreage'
      fullPath: '/guides/cover-crops-small-acreage'
      preLoaderRoute: typeof GuidesCoverCropsSmallAcreageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/days-to-maturity-fall-harvest': {
      id: '/guides/days-to-maturity-fall-harvest'
      path: '/guides/days-to-maturity-fall-harvest'
      fullPath: '/guides/days-to-maturity-fall-harvest'
      preLoaderRoute: typeof GuidesDaysToMaturityFallHarvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/direct-sow-vs-transplant': {
      id: '/guides/direct-sow-vs-transplant'
      path: '/guides/direct-sow-vs-transplant'
      fullPath: '/guides/direct-sow-vs-transplant'
      preLoaderRoute: typeof GuidesDirectSowVsTransplantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/drip-irrigation-quarter-acre': {
      id: '/guides/drip-irrigation-quarter-acre'
      path: '/guides/drip-irrigation-quarter-acre'
      fullPath: '/guides/drip-irrigation-quarter-acre'
      preLoaderRoute: typeof GuidesDripIrrigationQuarterAcreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/drip-irrigation-run-time': {
      id: '/guides/drip-irrigation-run-time'
      path: '/guides/drip-irrigation-run-time'
      fullPath: '/guides/drip-irrigation-run-time'
      preLoaderRoute: typeof GuidesDripIrrigationRunTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/microgreens-seed-density': {
      id: '/guides/microgreens-seed-density'
      path: '/guides/microgreens-seed-density'
      fullPath: '/guides/microgreens-seed-density'
      preLoaderRoute: typeof GuidesMicrogreensSeedDensityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/pasture-rest-days': {
      id: '/guides/pasture-rest-days'
      path: '/guides/pasture-rest-days'
      fullPath: '/guides/pasture-rest-days'
      preLoaderRoute: typeof GuidesPastureRestDaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/soil-blocking-transplants': {
      id: '/guides/soil-blocking-transplants'
      path: '/guides/soil-blocking-transplants'
      fullPath: '/guides/soil-blocking-transplants'
      preLoaderRoute: typeof GuidesSoilBlockingTransplantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/succession-planting-salad-greens': {
      id: '/guides/succession-planting-salad-greens'
      path: '/guides/succession-planting-salad-greens'
      fullPath: '/guides/succession-planting-salad-greens'
      preLoaderRoute: typeof GuidesSuccessionPlantingSaladGreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/succession-planting-schedule': {
      id: '/guides/succession-planting-schedule'
      path: '/guides/succession-planting-schedule'
      fullPath: '/guides/succession-planting-schedule'
      preLoaderRoute: typeof GuidesSuccessionPlantingScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/walk-in-cooler-management': {
      id: '/guides/walk-in-cooler-management'
      path: '/guides/walk-in-cooler-management'
      fullPath: '/guides/walk-in-cooler-management'
      preLoaderRoute: typeof GuidesWalkInCoolerManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irrigation/': {
      id: '/irrigation/'
      path: '/irrigation'
      fullPath: '/irrigation/'
      preLoaderRoute: typeof IrrigationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/irrigation/$slug': {
      id: '/irrigation/$slug'
      path: '/irrigation/$slug'
      fullPath: '/irrigation/$slug'
      preLoaderRoute: typeof IrrigationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nursery/': {
      id: '/nursery/'
      path: '/nursery'
      fullPath: '/nursery/'
      preLoaderRoute: typeof NurseryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nursery/$slug': {
      id: '/nursery/$slug'
      path: '/nursery/$slug'
      fullPath: '/nursery/$slug'
      preLoaderRoute: typeof NurserySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasture/': {
      id: '/pasture/'
      path: '/pasture'
      fullPath: '/pasture/'
      preLoaderRoute: typeof PastureIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasture/$slug': {
      id: '/pasture/$slug'
      path: '/pasture/$slug'
      fullPath: '/pasture/$slug'
      preLoaderRoute: typeof PastureSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/clipboard': {
      id: '/print/clipboard'
      path: '/print/clipboard'
      fullPath: '/print/clipboard'
      preLoaderRoute: typeof PrintClipboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil/': {
      id: '/soil/'
      path: '/soil'
      fullPath: '/soil/'
      preLoaderRoute: typeof SoilIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soil/$slug': {
      id: '/soil/$slug'
      path: '/soil/$slug'
      fullPath: '/soil/$slug'
      preLoaderRoute: typeof SoilSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClipRoute: ClipRoute,
  ClipboardRoute: ClipboardRoute,
  EngineRoute: EngineRoute,
  CropSlugRoute: CropSlugRoute,
  EconomicsSlugRoute: EconomicsSlugRoute,
  Guides30InchBedPrepRoute: Guides30InchBedPrepRoute,
  GuidesCoverCropsSmallAcreageRoute: GuidesCoverCropsSmallAcreageRoute,
  GuidesDaysToMaturityFallHarvestRoute: GuidesDaysToMaturityFallHarvestRoute,
  GuidesDirectSowVsTransplantRoute: GuidesDirectSowVsTransplantRoute,
  GuidesDripIrrigationQuarterAcreRoute: GuidesDripIrrigationQuarterAcreRoute,
  GuidesDripIrrigationRunTimeRoute: GuidesDripIrrigationRunTimeRoute,
  GuidesMicrogreensSeedDensityRoute: GuidesMicrogreensSeedDensityRoute,
  GuidesPastureRestDaysRoute: GuidesPastureRestDaysRoute,
  GuidesSoilBlockingTransplantsRoute: GuidesSoilBlockingTransplantsRoute,
  GuidesSuccessionPlantingSaladGreensRoute:
    GuidesSuccessionPlantingSaladGreensRoute,
  GuidesSuccessionPlantingScheduleRoute: GuidesSuccessionPlantingScheduleRoute,
  GuidesWalkInCoolerManagementRoute: GuidesWalkInCoolerManagementRoute,
  IrrigationSlugRoute: IrrigationSlugRoute,
  NurserySlugRoute: NurserySlugRoute,
  PastureSlugRoute: PastureSlugRoute,
  PrintClipboardRoute: PrintClipboardRoute,
  SoilSlugRoute: SoilSlugRoute,
  CropsIndexRoute: CropsIndexRoute,
  EconomicsIndexRoute: EconomicsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  IrrigationIndexRoute: IrrigationIndexRoute,
  NurseryIndexRoute: NurseryIndexRoute,
  PastureIndexRoute: PastureIndexRoute,
  SoilIndexRoute: SoilIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
